### ISSUE TITLE
Fail to fetch docker registry contents

### ISSUE THREAD

**Issue by MartinBurian** [swarmpit/swarmpit#167]
In swarmpit, when I try to create a new service from a docker image in our private GitLab registry, swarpit just says
`Obtaining the registry catalog failed. Enter the exact repository name to create service directly.`
The swarmpit logs:
```
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | Tue Oct 31 17:07:49 GMT 2017 [worker-2] ERROR - GET /distribution/registries/345675939d65605d027014d46a000b44/repositories
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | java.lang.ClassCastException: clojure.lang.Keyword cannot be cast to java.lang.String
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.util.response$find_header$fn__10395.invoke(response.clj:176)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.core$filter$fn__6893.invoke(core.clj:2794)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.lang.LazySeq.sval(LazySeq.java:40)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.lang.LazySeq.seq(LazySeq.java:49)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.lang.LazySeq.first(LazySeq.java:71)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.lang.RT.first(RT.java:682)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.core$first__6389.invokeStatic(core.clj:55)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.core$first__6389.invoke(core.clj:55)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.util.response$find_header.invokeStatic(response.clj:177)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.util.response$find_header.invoke(response.clj:170)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.util.response$get_header.invokeStatic(response.clj:184)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.util.response$get_header.invoke(response.clj:179)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.content_type$content_type_response.invokeStatic(content_type.clj:11)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.content_type$content_type_response.doInvoke(content_type.clj:6)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at clojure.lang.RestFn.invoke(RestFn.java:442)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.content_type$wrap_content_type$fn__11253.invoke(content_type.clj:31)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.default_charset$wrap_default_charset$fn__11268.invoke(default_charset.clj:31)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.not_modified$wrap_not_modified$fn__11229.invoke(not_modified.clj:52)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.x_headers$wrap_x_header$fn__10517.invoke(x_headers.clj:22)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.x_headers$wrap_x_header$fn__10517.invoke(x_headers.clj:22)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.x_headers$wrap_x_header$fn__10517.invoke(x_headers.clj:22)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at ring.middleware.gzip$wrap_gzip$fn__11375.invoke(gzip.clj:94)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
swarmpit_app.1.ih6woj6tby15@TPR-BaseVM    | 	at java.lang.Thread.run(Thread.java:745)
```

swarmpit 1.2-56f6f93

Please let me know if you need more information.

**Comment by nohaapav** [comment]
@MartinBurian Hi Martin .. we currently support only basic auth based registry .. gitlab is using custom auth token -> In version 1.3 we are going to support custom token based registry as well.
Check following issue and linked issues please:
https://github.com/swarmpit/swarmpit/issues/157
