### ISSUE TITLE
Docker failed: Permission denied

### ISSUE THREAD

**Issue by johnjelinek** [swarmpit/swarmpit#204]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

```
swarmpit.default(E): Feb 02, 2018 11:40:10 PM swarmpit.server invoke
swarmpit.default(E): INFO: Swarmpit is starting...
swarmpit.default(E): Feb 02, 2018 11:40:10 PM swarmpit.database invoke
swarmpit.default(E): INFO: Waiting for DB...
swarmpit.default(E): Feb 02, 2018 11:40:10 PM swarmpit.database invoke
swarmpit.default(E): INFO: ... connected after 0 sec
swarmpit.default(E): Feb 02, 2018 11:40:10 PM swarmpit.database invoke
swarmpit.default(E): INFO: DB schema created
swarmpit.default(O): Default token secret created
swarmpit.default(O): Default admin user created
swarmpit.default(E): Feb 02, 2018 11:40:13 PM swarmpit.server invoke
swarmpit.default(E): INFO: Swarmpit running on port 8080
swarmpit.default(E): Exception in thread "main" clojure.lang.ExceptionInfo: Docker failure: Permission denied {:status 500, :body {:error "Permission denied"}}
swarmpit.default(E): 	at clojure.core$ex_info.invokeStatic(core.clj:4725)
swarmpit.default(E): 	at clojure.core$ex_info.invoke(core.clj:4725)
swarmpit.default(E): 	at swarmpit.http$execute_in_scope.invokeStatic(http.clj:67)
swarmpit.default(E): 	at swarmpit.http$execute_in_scope.invoke(http.clj:53)
swarmpit.default(E): 	at swarmpit.docker.engine.http$execute.invokeStatic(http.clj:38)
swarmpit.default(E): 	at swarmpit.docker.engine.http$execute.invoke(http.clj:36)
swarmpit.default(E): 	at swarmpit.docker.engine.client$version.invokeStatic(client.clj:232)
swarmpit.default(E): 	at swarmpit.docker.engine.client$version.invoke(client.clj:230)
swarmpit.default(E): 	at swarmpit.setup$docker.invokeStatic(setup.clj:8)
swarmpit.default(E): 	at swarmpit.setup$docker.invoke(setup.clj:6)
swarmpit.default(E): 	at swarmpit.server$_main.invokeStatic(server.clj:66)
swarmpit.default(E): 	at swarmpit.server$_main.doInvoke(server.clj:59)
swarmpit.default(E): 	at clojure.lang.RestFn.invoke(RestFn.java:397)
swarmpit.default(E): 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
swarmpit.default(E): 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
swarmpit.default(E): 	at swarmpit.server.main(Unknown Source)
swarmpit.default(E): Fri Feb 02 23:41:13 GMT 2018 [timer-service] ERROR - In timer: timeout=60000ms, done or canceled
swarmpit.default(E): clojure.lang.ExceptionInfo: Docker failure: Permission denied {:status 500, :body {:error "Permission denied"}}
swarmpit.default(E): 	at clojure.core$ex_info.invokeStatic(core.clj:4725)
swarmpit.default(E): 	at clojure.core$ex_info.invoke(core.clj:4725)
swarmpit.default(E): 	at swarmpit.http$execute_in_scope.invokeStatic(http.clj:67)
swarmpit.default(E): 	at swarmpit.http$execute_in_scope.invoke(http.clj:53)
swarmpit.default(E): 	at swarmpit.docker.engine.http$execute.invokeStatic(http.clj:38)
swarmpit.default(E): 	at swarmpit.docker.engine.http$execute.invoke(http.clj:36)
swarmpit.default(E): 	at swarmpit.docker.engine.client$services.invokeStatic(client.clj:15)
swarmpit.default(E): 	at swarmpit.docker.engine.client$services.invoke(client.clj:13)
swarmpit.default(E): 	at swarmpit.api$services.invokeStatic(api.clj:444)
swarmpit.default(E): 	at swarmpit.api$services.invoke(api.clj:442)
swarmpit.default(E): 	at swarmpit.agent$autoredeploy_job.invokeStatic(agent.clj:9)
swarmpit.default(E): 	at swarmpit.agent$autoredeploy_job.invoke(agent.clj:7)
swarmpit.default(E): 	at swarmpit.agent$init$fn__19458.invoke(agent.clj:30)
swarmpit.default(E): 	at org.httpkit.timer.CancelableFutureTask.runTask(CancelableFutureTask.java:35)
swarmpit.default(E): 	at org.httpkit.timer.TimerService.run(TimerService.java:66)
swarmpit.default(E): 	at java.lang.Thread.run(Thread.java:745)
```

**Steps to reproduce the issue:**
1. `docker stack deploy -c ./docker-compose.yml swarmpit`

**What happens:**

I see some errors and a lot of `500`s in the browser.

**What should happen:**

no errors

**Additional information (e.g. docker version, cluster setup,...):**

Docker Swarm mode 17.09.1ce

**Comment by johnjelinek** [comment]
Ahh, seems that my issue was that I was running as a non-root user.
