### ISSUE TITLE
Resource monitoring doesn't work as expected

### ISSUE THREAD

**Issue by Dids** [swarmpit/swarmpit#272]
**Description**

I'm unable to see detailed resource usage/monitoring details in the "Nodes" view in Swarmpit.

![screenshot 2018-09-18 08 30 57](https://user-images.githubusercontent.com/3455449/45666273-a155ca80-bb1d-11e8-9f74-73a295373a11.png)

**Steps to reproduce the issue:**
1. Create a Docker Swarm cluster
2. Install Swarmpit
3. Check the "Nodes" page for resource usage

**What happens:**
Only CPU core count and memory amount are visible for each node.

**What should happen:**
I'd expect to see disk usage, as well as the percentages that are visible in the screenshots on the swarmpit.io website.

**Additional information (e.g. docker version, cluster setup,...):**

I have three node Docker Swarm cluster running, with two nodes running CoreOS and the last one running Ubuntu. All of them are seeing the same issue.

Docker version 18.06.1-ce, build e68fc7a

**Comment by rarous** [comment]
Hi @Dids, it depends on your cloud provider and their virtualisation of storage subsystem. Not all data are always provided or make sense.

**Comment by Dids** [comment]
Hmm, I see. Any chance of it being configurable, so I could work around it?

**Comment by lumir-mrkva** [comment]
@Dids it looks like the swarmpit agent isn't running correctly. can you provide me with more information about your installation? eg. `docker stack ps swarmpit`

**Comment by nohaapav** [comment]
@Dids You should be using swarmpit-agent instead of swarmpit_event-collector. Please check ROADMAP. Event collector went deprecated in new release.

**Comment by Dids** [comment]
Ah, thank you very much! Missed the deprecation entirely. Works like a charm now. 👍

**Comment by cpxPratik** [comment]
Resource monitoring is not working with swarmpit agent. Does it affect that it is deployed on DIgitalOcean?
![screenshot from 2019-03-07 13-28-53](https://user-images.githubusercontent.com/6893334/53940355-939cfd00-40dd-11e9-9e61-32d14e8dd015.jpg)

**Comment by nohaapav** [comment]
@cpxPratik Should work with DO as well. Is swarmpit-agent running properly ? What about tasks ? Are you able to see tasks stats or you have same issue ?

**Comment by cpxPratik** [comment]
@nohaapav Everything services, stacks, data volumes all works perfectly. Just node resource is not working. Yes, all agents are running properly. I also did `docker service update <service_name> --force`.

**Comment by cw1998** [comment]
I also have this issue on Scaleway instances. Everything else works fine, just node information that doesn't work correctly. Same issue as @cpxPratik

**Comment by cpxPratik** [comment]
`docker service logs swarm_services_swarmpit_agent` shows:
```
swarm_services_swarmpit_agent.0.b15a6v6unjms@develop-worker-01    | 2019/03/07 07:24:02 INFO: Waiting for Swarmpit...
swarm_services_swarmpit_agent.0.plwlfwh85bid@develop-worker-03    | 2019/03/07 06:31:28 INFO: Waiting for Swarmpit...
swarm_services_swarmpit_agent.0.no58vw59lqb2@develop-worker-02    | 2019/03/07 06:31:28 INFO: Waiting for Swarmpit...
swarm_services_swarmpit_agent.0.g8jyo9bi48r2@develop-worker-01    | 2019/03/07 06:31:28 INFO: Waiting for Swarmpit...
error from daemon in stream: Error grabbing logs: rpc error: code = Unknown desc = warning: incomplete log stream. some logs could not be retrieved for the following reasons: node wjtuicyg3gt71il9snr47pvgq is not available, node o7lksxiv7vvbecvgnrloqeg2n is not available

```

**Comment by nohaapav** [comment]
@cw1998 yes, running tasks should also show resource usage. Btw these instances are linux based ?

@cpxPratik You should see something like this in agent log in case of success:

```
swarmpit_agent.0.llzpfdbf5g4j@linuxkit-025000000001    | 2019/03/06 11:09:40 INFO: Waiting for Swarmpit...
swarmpit_agent.0.llzpfdbf5g4j@linuxkit-025000000001    | 2019/03/06 11:10:22 INFO: Swarmpit OK
swarmpit_agent.0.llzpfdbf5g4j@linuxkit-025000000001    | 2019/03/06 11:10:22 INFO: Event collector started.
swarmpit_agent.0.llzpfdbf5g4j@linuxkit-025000000001    | 2019/03/06 11:10:22 INFO: Stats collector started.
swarmpit_agent.0.llzpfdbf5g4j@linuxkit-025000000001    | 2019/03/06 11:10:22 INFO: Swarmpit agent listening on port 8080
```

**Comment by cw1998** [comment]
@nohaapav Yes, all Debian nodes. My logs also say `Waiting for Swarmpit...` on all nodes, so I will take a look into networks. Thanks for pointing that out. I'll report back here if I get anywhere.

**Comment by cw1998** [comment]
Got it. My issue was because the agent defaults the endpoints for the healthcheck to `app` 
In my configuration, I called it `swarmpit-app`. To fix this I added two new environment variables to the agent service:
`HEALTH_CHECK_ENDPOINT=http://swarmpit-app:8080/version`
`EVENT_ENDPOINT=http://swarmpit-app:8080/events`
where `swarmpit-app` is your app's service name.

**Comment by cpxPratik** [comment]
Thanks to everyone involved on this issue. I have used `swarmpit_app` than the assumed `app` for service name. :clap: @cw1998

**Comment by nohaapav** [comment]
Glad you figure this out guys :) ..

**Comment by bd8392** [comment]
We had exactly the same issue and the solution works! Thanks for that =). P.S.: Don't use your own swarmpit ports if you use other than 8080, use exactly the ports described above!

**Comment by nohaapav** [comment]
Yes, ports must match swarmpit container port within the swarmpit stack network, not the host port! .. And this port is always 8080 unless you change swarmpit image.

**Comment by allanyze** [comment]
Hello, I have exactly the same issues. 

![image](https://user-images.githubusercontent.com/5450748/118998183-d1835480-b9bb-11eb-90b4-ac07bc7ef126.png)

with logs "INFO: Waiting for Swarmpit..." on the worker nodes.

I have tried adding the following to the agent but it doesn't work.
HEALTH_CHECK_ENDPOINT=http://swarmpit-app:8080/version
EVENT_ENDPOINT=http://swarmpit-app:8080/events

Here are the logs:

Thu May UTC 2021 [worker-2] ERROR - GET /api/services/ts/memory
clojure.lang.ExceptionInfo: Malformed application/json in :muuntaja/encode {:type :muuntaja/encode, :format "application/json"}
        at muuntaja.core$on_exception.invokeStatic(core.clj:284)
        at muuntaja.core$on_exception.invoke(core.clj:267)
        at clojure.core$partial$fn__5839.invoke(core.clj:2626)
        at muuntaja.core$create_coder$encode__29981.invoke(core.clj:346)
        at clojure.core$update.invokeStatic(core.clj:6198)
        at clojure.core$update.invoke(core.clj:6188)
        at muuntaja.core$create$_handle_response__30048.invoke(core.clj:443)
        at muuntaja.core$create$reify__30050.format_response(core.clj:486)
        at muuntaja.middleware$wrap_format$fn__30107.invoke(middleware.clj:73)
        at reitit.ring$ring_handler$fn__27081.invoke(ring.cljc:292)
        at clojure.lang.AFn.applyToHelper(AFn.java:154)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:408)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:115)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.fasterxml.jackson.databind.JsonMappingException: (was java.lang.UnsupportedOperationException) (through reference chain: clojure.lang.PersistentArrayMap[":via"]->clojure.lang.PersistentVector[0]->clojure.lang.PersistentArrayMap[":data"]->clojure.lang.PersistentHashMap[":http-client"]->org.apache.http.impl.client.InternalHttpClient["params"])
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:394)
        at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:353)
        at com.fasterxml.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:155)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:718)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:718)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:119)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:79)
        at com.fasterxml.jackson.databind.ser.impl.IndexedListSerializer.serialize(IndexedListSerializer.java:18)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serializeFields(MapSerializer.java:718)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:639)
        at com.fasterxml.jackson.databind.ser.std.MapSerializer.serialize(MapSerializer.java:33)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._configAndWriteValue(ObjectMapper.java:3905)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsBytes(ObjectMapper.java:3243)
        at jsonista.core$write_value_as_bytes.invokeStatic(core.clj:229)
        at jsonista.core$write_value_as_bytes.invoke(core.clj:221)
        at muuntaja.format.json$encoder$reify__29618.encode_to_bytes(json.clj:43)
        at muuntaja.core$create_coder$encode__29981.invoke(core.clj:344)
        ... 16 more
Caused by: java.lang.UnsupportedOperationException
        at org.apache.http.impl.client.InternalHttpClient.getParams(InternalHttpClient.java:211)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:687)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
        ... 37 more

What could be the solution to fix this?
Thanks in advance.

**Comment by CyberDuck79** [comment]
Same problem as above comment :/

**Comment by mh3th** [comment]
@allanyze hello! the solution i found for myself.
swarmpit service should be named app.
and you don't need to add anything to the agent.
But for me there is still the question of how to change the name of the service swarmpit

**Comment by nohaapav** [comment]
@mh3th See following: https://github.com/swarmpit/agent#important 
@allanyze Looks like no data are yet collected by influx .. 

"INFO: Waiting for Swarmpit..." on the worker nodes. simply means that agent is unable to connect to swarmpit in order to send events/resource data timeseries etc ...

**Comment by Jagan-07** [comment]
To those who facing the issue "INFO: Waiting for Swarmpit..." and "Loading" for Worker nodes in the Swarmpit UI, I resolved this issue by opening the required ports correctly with the correct protocols. You can find the details below:

Open port 888 TCP - for Swarmpit UI.
Open port 2377 TCP - for communication with and between manager nodes.
Open port 7946 TCP and UDP - for overlay network node discovery.
Open port 4789 UDP - for overlay network traffic.

You can find the same information in the official Docker Swarm documentation:
https://docs.docker.com/engine/swarm/swarm-tutorial/#open-protocols-and-ports-between-the-hosts

**Comment by HamzaMohammadKhan** [comment]
Hey guys iam still having the same issue even after adding env variables in agent
The service for swarmpit is app, couchdb is db, influx is influxdb 

<img width="4080" height="3060" alt="Image" src="https://github.com/user-attachments/assets/11825391-49c9-4418-9d5d-dc57e9d0ce13" />

<img width="4080" height="3060" alt="Image" src="https://github.com/user-attachments/assets/56389249-599f-4a98-a48c-837bbf9dada9" />
