### ISSUE TITLE
Autoredeploy Problem

### ISSUE THREAD

**Issue by Greatsamps** [swarmpit/swarmpit#290]
We have just noticed an issue with autoredeploy having stopped working. We are running 1,000 services, and up until recently the autoredeploy was working well.

The nodes are aware of the new image digest, but none of the services have updated.

Can you advise steps to debug this?

**Comment by lumir-mrkva** [comment]
@Greatsamps can you check swarmpit log? its probably issue with access to the registry and it should be logged there

**Comment by nohaapav** [comment]
@Greatsamps Ho could you provide swarmpit_app log ?

**Comment by Greatsamps** [comment]
Where can i find this, is this just the docker logs for the swarmpit container?

**Comment by nohaapav** [comment]
@Greatsamps Yes

**Comment by Greatsamps** [comment]
So, problems have got worse over night. Looked at it this morning, and swarmpit is offline, can't connect to the database.

I checked container and it was stopped. I restated it, and checked logs. The logs are absolutely full of entries such as these:

[notice] 2018-12-13T19:13:59.418330Z nonode@nohost <0.30330.746> d1fd0496e0 db:5984 10.0.0.4 undefined POST /swarmpit/_find 200 ok 99
[notice] 2018-12-13T19:13:59.524952Z nonode@nohost <0.29162.746> 25da815915 db:5984 10.0.0.4 undefined POST /swarmpit/_find 200 ok 106
[notice] 2018-12-13T19:13:59.526269Z nonode@nohost <0.30508.746> fee3954959 db:5984 10.0.0.4 undefined POST /swarmpit/_find 200 ok 206
[notice] 2018-12-13T19:13:59.535200Z nonode@nohost <0.30288.746> c2e59cb78d db:5984 10.0.0.4 undefined POST /swarmpit/_find 200 ok 116
[notice] 2018-12-13T19:13:59.622117Z nonode@nohost <0.29964.746> 64c9f851c7 db:5984 10.0.0.4 undefined POST /swarmpit/_find 200 ok 199

Then just before it died, i got these errors:

[notice] 2018-12-13T19:13:59.641971Z nonode@nohost <0.395.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-13T19:13:59.643530Z nonode@nohost emulator -------- Error in process <0.29035.746> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[os_mon] memory supervisor port (memsup): Erlang has closed

I have restarted the container, but it still can't be accessed, and i have errors such as these:

[info] 2018-12-14T06:28:08.523143Z nonode@nohost <0.7.0> -------- Application setup started on node nonode@nohost
[info] 2018-12-14T06:28:08.523192Z nonode@nohost <0.7.0> -------- Application snappy started on node nonode@nohost
[error] 2018-12-14T06:28:11.834446Z nonode@nohost emulator -------- Error in process <0.522.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:11.834572Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-14T06:28:16.836115Z nonode@nohost emulator -------- Error in process <0.619.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:16.836200Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-14T06:28:21.838559Z nonode@nohost emulator -------- Error in process <0.684.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:21.838681Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-14T06:28:26.843703Z nonode@nohost emulator -------- Error in process <0.781.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:26.843791Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-14T06:28:31.845427Z nonode@nohost emulator -------- Error in process <0.846.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:31.845560Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)
[error] 2018-12-14T06:28:36.847308Z nonode@nohost emulator -------- Error in process <0.943.0> with exit value: {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,327}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,315}]},{mem3_shards,load_shards_from_disk...
[notice] 2018-12-14T06:28:36.847433Z nonode@nohost <0.379.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:327) <= mem3_shards:load_shards_from_disk/1(line:315) <= mem3_shards:load_shards_from_disk/2(line:331) <= mem3_shards:for_docid/3(line:87) <= fabric_doc_open:go/3(line:38) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:187) <= chttpd_auth_cache:listen_for_changes/1(line:134)


I suspect i am going to have to re-install swarmpit.

It also seems that the DB is logging every request that it gets. Is there a way to turn this off? As previously mentioned we have a lot of containers so the logs are getting very bloated.

Swarmpit is currently reporting these errors:

Fri Dec 14 06:40:56 GMT 2018 [worker-2] ERROR - POST /events
clojure.lang.ExceptionInfo: DB error: not_found {:status 404, :headers {"Cache-Control" "must-revalidate", "Connection" "close", "Content-Length" "58", "Content-Type" "application/json", "Date" "Fri, 14 Dec 2018 06:40:56 GMT", "Server" "CouchDB/2.0.0 (Erlang OTP/17)", "X-Couch-Request-ID" "79c8c5d535", "X-CouchDB-Body-Time" "0"}, :body {:error "not_found"}}
        at clojure.core$ex_info.invokeStatic(core.clj:4739)
        at clojure.core$ex_info.invoke(core.clj:4739)
        at swarmpit.http$execute_in_scope.invokeStatic(http.clj:76)
        at swarmpit.http$execute_in_scope.invoke(http.clj:53)
        at swarmpit.couchdb.client$execute.invokeStatic(client.clj:10)
        at swarmpit.couchdb.client$execute.invoke(client.clj:7)
        at swarmpit.couchdb.client$find_docs.invokeStatic(client.clj:37)
        at swarmpit.couchdb.client$find_docs.invoke(client.clj:33)
        at swarmpit.couchdb.client$find_doc.invokeStatic(client.clj:47)
        at swarmpit.couchdb.client$find_doc.invoke(client.clj:45)
        at swarmpit.couchdb.client$get_secret.invokeStatic(client.clj:107)
        at swarmpit.couchdb.client$get_secret.invoke(client.clj:105)
        at swarmpit.authentication$wrap_authentication$fn__17588.invoke(authentication.clj:28)
        at swarmpit.server$wrap_path_params$fn__18428.invoke(server.clj:42)
        at ring.middleware.json$wrap_json_params$fn__16672.invoke(json.clj:72)
        at ring.middleware.json$wrap_json_response$fn__16684.invoke(json.clj:87)
        at ring.middleware.flash$wrap_flash$fn__16728.invoke(flash.clj:39)
        at ring.middleware.session$wrap_session$fn__17068.invoke(session.clj:108)
        at ring.middleware.keyword_params$wrap_keyword_params$fn__17102.invoke(keyword_params.clj:36)
        at ring.middleware.nested_params$wrap_nested_params$fn__17152.invoke(nested_params.clj:89)
        at ring.middleware.multipart_params$wrap_multipart_params$fn__17309.invoke(multipart_params.clj:173)
        at ring.middleware.params$wrap_params$fn__17325.invoke(params.clj:67)
        at ring.middleware.cookies$wrap_cookies$fn__16977.invoke(cookies.clj:175)
        at ring.middleware.absolute_redirects$wrap_absolute_redirects$fn__17432.invoke(absolute_redirects.clj:47)
        at ring.middleware.resource$wrap_resource$fn__17345.invoke(resource.clj:37)
        at ring.middleware.content_type$wrap_content_type$fn__17396.invoke(content_type.clj:34)
        at ring.middleware.default_charset$wrap_default_charset$fn__17412.invoke(default_charset.clj:31)
        at ring.middleware.not_modified$wrap_not_modified$fn__17378.invoke(not_modified.clj:53)
        at ring.middleware.x_headers$wrap_x_header$fn__16699.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__16699.invoke(x_headers.clj:22)
        at ring.middleware.x_headers$wrap_x_header$fn__16699.invoke(x_headers.clj:22)
        at ring.middleware.gzip$wrap_gzip$fn__17522.invoke(gzip.clj:100)
        at org.httpkit.server.HttpHandler.run(RingHandler.java:91)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

which will be related to the DB problem. The logs are full of these entries and can't go back before them, so will need to sort this, then try an autoredeploy again.

Is there any way i can recreate the DB from scratch? and turn off the verbose DB logging?

**Comment by nohaapav** [comment]
@Greatsamps These DB logs are harmless and described here: 
https://github.com/swarmpit/swarmpit/issues/192. We're aware of it and will be fixing that soon.

Although this really looks like swarmpit can't connect DB for some reason:
```
Fri Dec 14 06:40:56 GMT 2018 [worker-2] ERROR - POST /events
clojure.lang.ExceptionInfo: DB error: not_found {:status 404, :headers {"Cache-Control" "must-revalidate", "Connection" "close", "Content-Length" "58", "Content-Type" "application/json", "Date" "Fri, 14 Dec 2018 06:40:56 GMT", "Server" "CouchDB/2.0.0 (Erlang OTP/17)", "X-Couch-Request-ID" "79c8c5d535", "X-CouchDB-Body-Time" "0"}, :body {:error "not_found"}}
```
It might be broken overlay, not enough space or just engine restart ..

Well you can recreate DB by dropping volume and deleting db service -> then new one will be spawned once stack redeployed, or you can setup DB manually .. Actually what swarmpit does to create DB is run this simple query:

```
(defn create-database
  []
  (-> (execute {:method :PUT
                :api    "/swarmpit"})
      :body))
```

behind the scenes during initialization phase.

**Comment by nohaapav** [comment]
Closing due to inactivity. Reopen if issue still persist ;)

**Comment by dedupely** [comment]
I have an issue with autoredeploy. I've deleted the old logins for the docker hub and repository thinking it was an auth error. Still the same.

When I look at the swarmpit_agent service I see a bunch of event errors (not sure what this actually means)
```
swarmpit_agent.0.zc8hby55oalx@gce-beanstalkd-node    | 2018/12/22 01:57:37 INFO: Waiting for Swarmpit...
swarmpit_agent.0.zc8hby55oalx@gce-beanstalkd-node    | 2018/12/22 01:57:42 INFO: Swarmpit OK
swarmpit_agent.0.zc8hby55oalx@gce-beanstalkd-node    | 2018/12/22 01:57:42 INFO: Event collector started.
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:43:54 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:43:54 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:43:54 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:43:54 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:44:18 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:44:23 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:44:55 ERROR: Event sending failed: Post http://app:8080/events: dial tcp 10.0.4.7:8080: getsockopt: connection refused
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/11/29 02:45:27 ERROR: Event sending failed: Post http://app:8080/events: dial tcp 10.0.4.7:8080: getsockopt: connection refused
swarmpit_agent.0.yhms5a3gynws@dedupelyv4-manager3-calgary    | 2018/12/18 10:05:17 ERROR: Event sending failed: Post http://app:8080/events: dial tcp: lookup app on 127.0.0.11:53: no such host
```

Looking at the _app service, I notice a bunch of error logs from Dec 11 (a month ago from posting this)
```
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 7:55:32 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 07:55:32 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 7:56:42 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 07:56:42 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 7:57:51 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 07:57:51 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 7:59:00 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 07:59:00 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 8:00:11 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 08:00:11 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 8:01:21 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 08:01:21 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 8:02:31 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 08:02:30 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 8:03:40 AM swarmpit.agent invoke
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | SEVERE: Service i9tq4xkbcptwrph602j9m8tnw autoredeploy failed!  {:status 404, :headers {Content-Type application/json; charset=utf-8, Docker-Distribution-Api-Version registry/2.0, Date Tue, 11 Dec 2018 08:03:40 GMT, Content-Length 96, Connection close, Strict-Transport-Security max-age=31536000}, :body {:error manifest unknown}}
swarmpit_app.1.f18e9q5auaq8@dedupelyv4-manager2-calgary    | Dec 11, 2018 8:04:49 AM swarmpit.agent invoke
```
Not sure if that has anything to do with it. Those are the last logs I can find.

I doubled checked my services to make sure they had the label:

```
    deploy:
      replicas: 20
      labels:
        swarmpit.service.deployment.autoredeploy: 'true'
```

and they do.

I'm running swarmpit 1.5 and docker version 18.06.1-ce

Everything else runs perfectly, no issues at all, besides this.

**Comment by nohaapav** [comment]
@dedupely Hi agent issue looks like broken swarm overlay .. Agent just can't find swarmpit_app .. try to redeploy that to fix it.

Regarding autoredeploy .. From that logs it looks like dockerhub api returns not found for given service image .. will check that out

**Comment by dedupely** [comment]
I'm not sure if Docker Hub changed some things in their API but I heard that Hub and Cloud were supposed to merge but I'm not sure if that's true.
