### ISSUE TITLE
Swarmpit container is permanently rebuilt. also after docker system prune

### ISSUE THREAD

**Issue by valentinwinkelmann** [swarmpit/swarmpit#313]
Hello. i somehow screwed up the installation. i suddenly had 3 containers after the installation. i unfortunately deleted one of them, maybe that started the error, i can't get swarmpit stopped anymore. i already deleted everything with the two commands, but immediately after that 2 new containers appear.

the code i use to stop everything and prune then all:
`docker container stop $(docker container ls -a -q) && docker system prune -a -f --volumes`

I installed swarmpit via git as it says in the readme.

how can i break this infinite circle to reinstall swarmpit cleanly again? i enclose the logs of the individual docker containers

The first Docker Container says this in the log

```
Feb 14, 2019 8:30:57 PM swarmpit.server invoke
INFO: Swarmpit is starting...
Feb 14, 2019 8:30:57 PM swarmpit.database invoke
INFO: Waiting for DB...
Feb 14, 2019 8:32:37 PM swarmpit.database invoke
SEVERE: ... timeout
Exception in thread "main" java.lang.IllegalArgumentException: Additional data must be non-nil.
	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:31)
	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:22)
	at clojure.core$ex_info.invokeStatic(core.clj:4783)
	at clojure.core$ex_info.invoke(core.clj:4783)
	at swarmpit.database$wait_for_db.invokeStatic(database.clj:20)
	at swarmpit.database$wait_for_db.invoke(database.clj:11)
	at swarmpit.database$init.invokeStatic(database.clj:34)
	at swarmpit.database$init.invoke(database.clj:32)
	at swarmpit.server$_main.invokeStatic(server.clj:60)
	at swarmpit.server$_main.doInvoke(server.clj:58)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at swarmpit.server.main(Unknown Source)
```

and the second says this

```
2019/02/14 20:30:34 INFO: Waiting for Swarmpit...
```
EDIT:
now i even completely uninstalled and reinstalled docker. but the cycle is not stopped, there are new docker containers immediately and they will be rebuilt.

I hope you can help me somehow. 🤔

**Comment by lumir-mrkva** [comment]
seems like you removed swarmpit_db, you should be able to fix swarmpit stack by simply running ```docker stack up -c swarmpit/docker-compose.yml ```

**Comment by lumir-mrkva** [comment]
btw. you cannot remove service by removing it's containers, service will always try to start containers again, if you want to remove stack or service from swarm, you should use `docker service rm` and `docker stack rm` respectivelly

**Comment by valentinwinkelmann** [comment]
@lumir-mrkva 
Thank you so much. That worked wonders. I was already despairing. Great that you answered so quickly.
And also thanks for the link, I am very unexperienced in handling swarms. I will definitely take a look at it.

**Comment by JustinBeaudry** [comment]
To fix swarmpit stack I had to run:

```
docker stack deploy swarmpit --compose-file docker-compose.yml
```
