### ISSUE TITLE
Using an external node as CouchDB

### ISSUE THREAD

**Issue by atmosx** [swarmpit/swarmpit#322]
Hello!

I'm trying to setup swarpit for testing purposes on a staging cluster. I don't wanna use cloudstor or rexray. I'm starting swarmpit with the following env vars (I'm using the docker-py for deployments):

```
`env=["SWARMPIT_DB={}".format(couchdb_uri), "SWARMPIT_DOCKER_SOCK=tcp://socat:2375"]`
```

The docker socket is accessible through socat TCP.  The `couchdb_uri` points to a CouchDB running on a dedicated node, through docker-compose.  The CouchDB docker-compose looks like this:

```
version: '3.3'

services:
  db:
    image: couchdb:2.3.0
    volumes:
      - couchdb-data:/opt/couchdb/data
    ports:
      - 5984:5984
      - 4369:4369
      - 9100:9100

volumes:
  couchdb-data:
```

The logs on swarmpit (running on docker swarm):

```
# docker service logs swarmpit -f
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Mar 07, 2019 7:46:22 PM swarmpit.server invoke
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | INFO: Swarmpit is starting...
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Mar 07, 2019 7:46:22 PM swarmpit.database invoke
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | INFO: Waiting for DB...
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Mar 07, 2019 7:46:23 PM swarmpit.database invoke
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | INFO: ... connected after 0 sec
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Mar 07, 2019 7:46:23 PM swarmpit.database invoke
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | INFO: DB schema created
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Single node setup finished
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Default token secret created
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Mar 07, 2019 7:46:23 PM swarmpit.server invoke
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | INFO: Swarmpit running on port 8080
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    | Exception in thread "main" clojure.lang.ExceptionInfo: Docker failure: No such file or directory {:status 500, :body {:error "No such file or directory"}}
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.http$execute_in_scope.invokeStatic(http.clj:67)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.http$execute_in_scope.invoke(http.clj:53)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.docker.engine.http$execute.invokeStatic(http.clj:41)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.docker.engine.http$execute.invoke(http.clj:39)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.docker.engine.client$version.invokeStatic(client.clj:287)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.docker.engine.client$version.invoke(client.clj:285)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.setup$docker.invokeStatic(setup.clj:8)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.setup$docker.invoke(setup.clj:6)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.server$_main.invokeStatic(server.clj:65)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.server$_main.doInvoke(server.clj:58)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at clojure.lang.RestFn.invoke(RestFn.java:397)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at clojure.lang.AFn.applyToHelper(AFn.java:152)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at clojure.lang.RestFn.applyTo(RestFn.java:132)
swarmpit.1.wrpz2ns9eczm@ip-10-0-12-27    |      at swarmpit.server.main(Unknown Source)
```

In CouchDB node:

```
db_1  | [notice] 2019-03-07T19:46:23.387446Z nonode@nohost <0.827.0> 2985b7f0c6 couchdb-internal.server.com:5984 10.0.12.27 undefined GET / 200 ok 18
db_1  | [error] 2019-03-07T19:46:23.472067Z nonode@nohost <0.828.0> 27421c888c Request to create N=3 DB but only 1 node(s)
db_1  | [notice] 2019-03-07T19:46:23.568310Z nonode@nohost <0.828.0> 27421c888c couchdb-internal.server.com:5984 10.0.12.27 undefined PUT /swarmpit 201 ok 103
db_1  | [notice] 2019-03-07T19:46:23.613899Z nonode@nohost <0.829.0> ca83e7993a couchdb-internal.server.com:5984 10.0.12.27 undefined POST /swarmpit/_find 200 ok 36
db_1  | [error] 2019-03-07T19:46:23.621571Z nonode@nohost <0.830.0> 7f8f181182 Request to create N=3 DB but only 1 node(s)
db_1  | [notice] 2019-03-07T19:46:23.712812Z nonode@nohost <0.830.0> 7f8f181182 couchdb-internal.server.com:5984 10.0.12.27 undefined PUT /_users 201 ok 92
db_1  | [error] 2019-03-07T19:46:23.717305Z nonode@nohost <0.831.0> ad27aa42af Request to create N=3 DB but only 1 node(s)
db_1  | [notice] 2019-03-07T19:46:23.745777Z nonode@nohost <0.484.0> -------- creating replicator ddoc <<"shards/80000000-9fffffff/_replicator.1551987983">>
db_1  | [error] 2019-03-07T19:46:23.766649Z nonode@nohost emulator -------- Error in process <0.979.0> with exit value:
db_1  | {database_does_not_exist,[{mem3_shards,load_shards_from_db,"_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem
3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,54}]},{fabric,reset_validation_funs,1,[{file,"src/fabric.erl"},{line,480}]}]}
db_1  |
db_1  | [notice] 2019-03-07T19:46:23.776974Z nonode@nohost <0.831.0> ad27aa42af couchdb-internal.server.com:5984 10.0.12.27 undefined PUT /_replicator 201 ok 60
db_1  | [error] 2019-03-07T19:46:23.777257Z nonode@nohost emulator -------- Error in process <0.219.0> with exit value:
db_1  | {{'EXIT',{{'EXIT',{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"}
,{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,54}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,146}]},{couch_index_server,handle_db_event,3,[{file,"src/couch_index_serv
er.erl"},{line,281}]},{couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event_listener_mfa.erl"},{line,85}]},{couch_event_listener,do_event,3,[{file,"src/couch_event_listener.erl"},{line,142}]}]}},[{
couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event_listener_mfa.erl"},{line,91}]},{couch_event_listener,do_event,3,[{file,"src/couch_event_listener.erl"},{line,142}]}]}},[{couch_event_listener,do
_event,3,[{file,"src/couch_event_listener.erl"},{line,150}]}]}
db_1  |
db_1  | [error] 2019-03-07T19:46:23.779005Z nonode@nohost <0.217.0> -------- gen_server couch_index_server terminated with reason: {'EXIT',{{'EXIT',{database_does_not_exist,[{mem3_shards,load_shards_from_db,"
_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,54}]},{mem3_sh
ards,local,1,[{file,"src/mem3_shards.erl"},{line,146}]},{couch_index_server,handle_db_event,3,[{file,"src/couch_index_server.erl"},{line,281}]},{couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event
_..."},...]},...]}},...}} at couch_event_listener:do_event/3(line:150) at couch_index_server:handle_info/2(line:190) <= gen_server:try_dispatch/4(line:601) <= gen_server:handle_msg/5(line:667) <= proc_lib:ini
t_p_do_apply/3(line:247)
db_1  |   last msg: {'EXIT',<0.219.0>,{{'EXIT',{{'EXIT',{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1
,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,54}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,146}]},{couch_index_server,handle_db_event,
3,[{file,"src/couch_index_server.erl"},{line,281}]},{couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event_listener_mfa.erl"},{line,85}]},{couch_event_listener,do_event,3,[{file,"src/couch_event_lis
tener.erl"},{line,142}]}]}},[{couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event_listener_mfa.erl"},{line,91}]},{couch_event_listener,do_event,3,[{file,"src/couch_event_listener.erl"},{line,142}]
}]}},[{couch_event_listener,do_event,3,[{file,"src/couch_event_listener.erl"},{line,150}]}]}}
db_1  |      state: {st,"./data"}
db_1  |     extra: []
db_1  | [error] 2019-03-07T19:46:23.781951Z nonode@nohost <0.217.0> -------- CRASH REPORT Process couch_index_server (<0.217.0>) with 0 neighbors exited with reason: {'EXIT',{{'EXIT',{database_does_not_exist,
[{mem3_shards,load_shards_from_db,"_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,for_db,2,[{file,"src/mem
3_shards.erl"},{line,54}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,146}]},{couch_index_server,handle_db_event,3,[{file,"src/couch_index_server.erl"},{line,281}]},{couch_event_listener_mfa,han
dle_event,3,[{file,"src/couch_event_..."},...]},...]}},...}} at couch_event_listener:do_event/3(line:150) at gen_server:terminate/7(line:812) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_inde
x_server,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.206.0>], messages: [], links: [<0.215.0>], dictionary: [], trap_exit: true, status: running, heap_size: 2586, stack_size: 27,
reductions: 9482
db_1  | [error] 2019-03-07T19:46:23.782747Z nonode@nohost <0.215.0> -------- Supervisor couch_secondary_services had child index_server started with couch_index_server:start_link() at <0.217.0> exit with reas
on {'EXIT',{{'EXIT',{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_replicator",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line
,370}]},{mem3_shards,for_db,2,[{file,"src/mem3_shards.erl"},{line,54}]},{mem3_shards,local,1,[{file,"src/mem3_shards.erl"},{line,146}]},{couch_index_server,handle_db_event,3,[{file,"src/couch_index_server.erl
"},{line,281}]},{couch_event_listener_mfa,handle_event,3,[{file,"src/couch_event_..."},...]},...]}},...}} at couch_event_listener:do_event/3(line:150) in context child_terminated
db_1  | [error] 2019-03-07T19:46:23.784136Z nonode@nohost <0.832.0> 88cf26298c Request to create N=3 DB but only 1 node(s)
db_1  | [notice] 2019-03-07T19:46:23.843173Z nonode@nohost <0.832.0> 88cf26298c couchdb-internal.server.com:5984 10.0.12.27 undefined PUT /_global_changes 201 ok 61
db_1  | [notice] 2019-03-07T19:46:23.868649Z nonode@nohost <0.833.0> a00229cf7b couchdb-internal.server.com:5984 10.0.12.27 undefined POST /swarmpit 201 ok 21
db_1  | [notice] 2019-03-07T19:46:23.878816Z nonode@nohost <0.834.0> 13096f844f couchdb-internal.server.com:5984 10.0.12.27 undefined POST /swarmpit/_find 200 ok 6
db_1  | [notice] 2019-03-07T19:46:23.897047Z nonode@nohost <0.835.0> 93f7f53850 couchdb-internal.server.com:5984 10.0.12.27 undefined POST /swarmpit 201 ok 14
db_1  | [notice] 2019-03-07T19:46:23.918060Z nonode@nohost <0.836.0> a7498927a2 couchdb-internal.server.com:5984 10.0.12.27 undefined POST /swarmpit 201 ok 17
```

The CouchDB docker-compose have lots of logs but finally it seems to boot and create the DB successfully. Additionally, are there any instructions for running CouchDB in a non-swarm node? It seems like neither standalone or "none" (not configured) node seems to work out of the box.

**Comment by atmosx** [comment]
It actually worked. The TCP socket didn't worked, I'm running on a manager node, I'll just make sure it's not the leader. Thanks for the software :-) - closing this.

**Comment by nohaapav** [comment]
@atmosx You can run couchDB on worker node .. No issue with that at all :) We do the same.
