### ISSUE TITLE
on see logs sometimes get "Cannot form URI without a value given for :id parameter" console error

### ISSUE THREAD

**Issue by amitm02** [swarmpit/swarmpit#375]
In version 1.7 from docker hub: sometimes when clicking on service->logs i get an empty page with the console error:

```
Uncaught 
Mk
Pf: null
columnNumber: undefined
data: k {meta: null, I: 0, B: Array(0), D: -15128758, o: 16647951, …}
description: undefined
fileName: undefined
lineNumber: undefined
message: "Cannot form URI without a value given for :id parameter"
name: "Error"
number: undefined
stack: "Error: Cannot form URI without a value given for :id parameter↵    at new Mk (http://localhost:888/js/main.js:12249:24)↵    at Ok (http://localhost:888/js/main.js:12250:270)↵    at D.f.Je (http://localhost:888/js/main.js:12340:353)↵    at kz (http://localhost:888/js/main.js:12335:499)↵    at http://localhost:888/js/main.js:12348:124↵    at http://localhost:888/js/main.js:11990:291↵    at http://localhost:888/js/main.js:11990:304↵    at wg (http://localhost:888/js/main.js:11927:436)↵    at vg.f.V (http://localhost:888/js/main.js:11930:266)↵    at r (http://localhost:888/js/main.js:11852:83)"
__proto__: Error
```

**Comment by nohaapav** [comment]
Interesting. Can you check the network section for queries that were called ?

**Comment by Lurk** [comment]
Have same issue on 1.8-bf65377

Here screenshot of network section
![image](https://user-images.githubusercontent.com/426748/61359220-99bd9a00-a884-11e9-821c-844e30019eb8.png)

**Comment by nohaapav** [comment]
This looks ok. Basically the error above says that the `since` parameter in log API call was not specified so uri to backend cannot be formed. I'll check the codebase, probably we did not cover
some scenario :)

**Comment by Masa331** [comment]
Same thing happens to me quite often. Write me on Slack if some more info would help

**Comment by mentatxx** [comment]
Got same error. May be related to case when logs are not created yet (service is starting, or not produced logs yet)

**Comment by kerhong** [comment]
Also getting the same error. Tried debugging, but cannot reproduce when not compiled in for production.

I don't think this is related to lack of logs. I think there is a race condition that results in `log-handler` being called with `service-id = undefined`.

I tried, but was unable to get prod build with source maps, I could try to investigate this further if someone can assist with how to create a production build with source maps.
