### ISSUE TITLE
Unable to run repl and figwheel

### ISSUE THREAD

**Issue by tigp** [swarmpit/swarmpit#381]
Followed the [CONTRIBUTING.md](https://github.com/swarmpit/swarmpit/blob/master/CONTRIBUTING.md) guide I couldn't run figwheel and repl.

I got an error running repl:
```
ERROR: Unhandled REPL handler exception processing message {:id 4077c250-0a26-4c61-976d-69d5d296c22e, :op clone}
java.lang.NullPointerException
	at clojure.core$deref_future.invokeStatic(core.clj:2300)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at cemerick.piggieback$wrap_cljs_repl$fn__16166.invoke(piggieback.clj:289)
	at clojure.tools.nrepl.middleware$wrap_conj_descriptor$fn__11518.invoke(middleware.clj:22)
	at nrepl.server$handle_STAR_.invokeStatic(server.clj:18)
	at nrepl.server$handle_STAR_.invoke(server.clj:15)
	at nrepl.server$handle$fn__15747.invoke(server.clj:27)
	at clojure.core$binding_conveyor_fn$fn__5739.invoke(core.clj:2030)
	at clojure.lang.AFn.call(AFn.java:18)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Wo
```
I was able to solve it replacing piggieback with the latest cider version, but figwheel still hangs on 
```Prompt will show when Figwheel connects to your application```

Java 1.8.0_221
Lein 2.9.1

**Comment by lumir-mrkva** [comment]
hi, glad you're trying our dev environment.

unfortunately, none of us is using cider, is this happening even when you run `lein repl` from the console? does this happen after calling `run` function or even before it? does `lein uberjar` finish successfully?

**Comment by tigp** [comment]
Hi @lumir-mrkva Thank you for quick reply! And for this great app!

It stops before allowing to enter any commands.
Maybe there are any setup requirements we should take care of?

**Comment by lumir-mrkva** [comment]
@tigp leiningen 2.8.2 switched to different nrepl package, i updated dependencies accordingly, so it should be working now

**Comment by tigp** [comment]
@lumir-mrkva thank you very much for your help, I think we would spend quite a lot of time figuring this out.

Thanks and have a great day!
