### ISSUE TITLE
Possible memory/resource leak when using autoredeploy on a service stored in AWS ECR

### ISSUE THREAD

**Issue by irstevenson** [swarmpit/swarmpit#471]
**Description**

After running swarmpit 1.8 for a couple of months with no issues (and previous versions for over a year), I was suddenly having memory issues with my manager node. Turned out the swarmpit container was sitting around 4GiB.

I restarted the container (just with a swarmpit redeploy - which worked surprisingly), but then about 3 days later it was back up around 4GiB again. However this time swarpit UI became unresponsive (errors popping up about system threads, etc), and I was also unable to SSH into the machine (reporting broken pipes, shell requests failing), resulting in a need to do a reboot of the machine.

After the reboot I noted the memory was still slowly increasing. (Tracking both via the Swarmpit dashboard - I have the influxdb support active - as well as metricbeat into elasticsearch and kibana.)

Now the main thing that has changed, we have attempted to utilise the autoredploy feature for the first time, and it's against our AWS ECR (private) registry which we also only recently decided to try the support for.

At first it seemed maybe it was a coincidence, but with the memory still going up after the reboot I switched off the autoredeploy for that service. And since then (almost 24 hours later) the memory has stablised again.

Supporting memory % usage graph (metricbeat/kibana):

![image](https://user-images.githubusercontent.com/7528551/74690665-055d5080-5234-11ea-8a8f-b6c3a3c25d6b.png)

Swarmpit UI graph:

![image](https://user-images.githubusercontent.com/7528551/74690693-28880000-5234-11ea-93f6-9cbbc80c77f2.png)

**Steps to reproduce the issue:**

My guess would be:

1. Add an AWS ECR registry to swarmpit
2. Add a stack with a service using an image from the AWS ECR registry (note: the image doesn't even need to be receiving updates for this to occur)
3. Turn on the autoredeploy via the UI - for that service 
4. Monitor memory

**Additional information (e.g. docker version, cluster setup,...):**

* 3 node cluster - two worker, one manager
* 8 GiB RAM each node
* AWS EC2 instances
* docker 18.09.2
* debian 9.8
* Cluster is relatively low load (only 36 running tasks) - it's our dev cluster, not production

![image](https://user-images.githubusercontent.com/7528551/74690885-b368fa80-5234-11ea-825a-da5de21506d1.png)

**Comment by nohaapav** [comment]
@irstevenson Meanwhile you can use redeploy api which does the same trick.

**Comment by irstevenson** [comment]
Thansk @nohaapav , I'll have a look into that, as currently (and previously) we simply have done all our refreshes via a cron job on the manager using the docker CLI. But I've always wanted to be able to utilise the swarmpit inbuilt redeploy, so as soon as I got to try the new AWS ECR support I was pretty excited. ;)

**Comment by nohaapav** [comment]
@irstevenson It's pretty simple .. you just have to generate token and call `service/{id}/redeploy` API. We'll take a look into autoredeploy meanwhile. There is basically cron in swarmpit checking registry every minute for new digest  and most probably this process is causing the issue with ECR.

**Comment by yourapiexpert** [comment]
I would like to confirm the findings above.  I have swarmpit:latest installed on our dev cluster and also have autoredeploy enabled against our ECR.  I am sure it's not ECR specific but as you will see from this graph there is a stady increase in the RAM utilization over time until the UI becomes unresponsive and needs a kick.

![image](https://user-images.githubusercontent.com/25435508/75698783-47819a00-5cea-11ea-91f9-2a0a73ab1901.png)

My heartfelt thanks to the folks behind this truly excellent UI.  It makes our lives so much easier.

**Comment by layerssss** [comment]
@nohaapav I think I was running into this as well. I setup a new swarm with this and a few apps, then enabled the auto-deploy (I have also added a "v2" private registry). The memory was growing pretty fast and quickly the `swarmpit_app` service becomes unresponsive and eating all the cpu cap it has (50%) on my setting. In logs there were bunch of lines of

```
Exception in thread "async-dispatch-182" java.lang.OutOfMemoryError: Java heap space
```

I saw this thread then I turned off all auto-deployment the restarted the swarm but it still kept running into unresponsive and OutOfMemoryError every ~10 minutes.

So I guess I'm hitting the same error. My setup is clean and simple so I quickly checked into the couchdb to see what is it trying to do with this simple setup. And one thing I found out suspicious is that the registry document (found using `type: { $eq: "v2" }`) is enormous. I quickly deleted that and things went back to normal after a restart and re-adding the registry entry.

Sorry, I should have saved the huge "v2" document for debug the issue. But meanwhile I'll see if I can reproduce the situation by turning back on the auto-deploy and play with it. I'll post the document here if it comes up again.

**Comment by nohaapav** [comment]
@layerssss Hi thanks for info. Basically document should contain just v2 database setup, nothing else. For each v2 registry linked with swarmpit one related document should be created .. Would be great if you can reproduce the issue and share doc info ..

**Comment by dancernogorsky** [comment]
Same issue. Runs great for a few days, then becomes unresponsive.
I redeploy the stack the process get it back online.

[Link to Logs](https://gist.github.com/dancernogorsky/b71dab4c6a658dfec0f5d95acee716b5)

**Comment by nohaapav** [comment]
@dancernogorsky Thanks for logs. I'll take a look into the issue,

**Comment by layerssss** [comment]
It seems I can't reproduce the case where the "registry" doc is polluted any more, but I still kept running into memory leak. (I added resource limit and healthcheck so I can see it's becoming unresponsive and restarting every ~1 hour)

![image](https://user-images.githubusercontent.com/1559832/84340475-f0e30080-abf4-11ea-8847-32ac418d021f.png)

Here's the last log of last failed task and my healthcheck defined in the stack compose file.

https://gist.github.com/layerssss/0decdc29fe5ddbf0bb51fb73e7979ec9

But it doesn't seem to contain a lot useful information, is there a way to make the logging more verbose?

**Comment by nohaapav** [comment]
@layerssss 

Following is quite useful: 

https://gist.github.com/layerssss/0decdc29fe5ddbf0bb51fb73e7979ec9#file-swarmpit_app-log-L100

```
 Exception in thread "async-dispatch-33" clojure.lang.ExceptionInfo: Docker error: Request timeout {:status 408, :type :http-client, :body {:error "Request timeout"}}
```

**Comment by vpistis** [comment]
Hi,

we have same error using private servers:
```
Exception in thread "async-dispatch-1" java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Arrays.java:3332)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)
        at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)
        at java.lang.StringBuilder.append(StringBuilder.java:136)
        at clojure.core$str$fn__5451.invoke(core.clj:557)
        at clojure.core$str.invokeStatic(core.clj:555)
        at clojure.core$str.doInvoke(core.clj:544)
        at clojure.lang.RestFn.invoke(RestFn.java:439)
        at swarmpit.event.channel$event_data.invokeStatic(channel.clj:18)
        at swarmpit.event.channel$event_data.invoke(channel.clj:16)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309$fn__19317.invoke(channel.clj:77)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309.invoke(channel.clj:73)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307.invoke(channel.clj:71)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at swarmpit.event.channel$broadcast_statistics$fn__19306.invoke(channel.clj:71)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by nohaapav** [comment]
In latest version we're using `chime` instead of `httpkit` scheduler .. This one has failover and should perform better so check it out.

 We also upgrade from old java 8 to 11.
