### ISSUE TITLE
setting SWARMPIT_DOCKER_HTTP_TIMEOUT cause java.lang.ClassCastException

### ISSUE THREAD

**Issue by mapo-job** [swarmpit/swarmpit#511]
**Description**
Using swarmpit 1.9, Setting 

```
    environment:
      - SWARMPIT_DOCKER_HTTP_TIMEOUT=30000
```

for the swarmpit service will cause a ClassCastException.

This is the log: 

Exception in thread "async-dispatch-25" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
        at clojure.core$deref.invokeStatic(core.clj:2323)
        at clojure.core$deref.invoke(core.clj:2306)
        at swarmpit.http$execute_in_scope$fn__6006.invoke(http.clj:60)
        at swarmpit.http$execute_in_scope.invokeStatic(http.clj:60)
        at swarmpit.http$execute_in_scope.invoke(http.clj:54)
        at swarmpit.docker.engine.http$execute.invokeStatic(http.clj:39)
        at swarmpit.docker.engine.http$execute.invoke(http.clj:37)
        at swarmpit.docker.engine.client$nodes.invokeStatic(client.clj:272)
        at swarmpit.docker.engine.client$nodes.invoke(client.clj:270)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.AFn.applyTo(AFn.java:144)
        at clojure.core$apply.invokeStatic(core.clj:665)
        at clojure.core$apply.invoke(core.clj:660)
        at clojure.core.memoize$through_STAR_$fn__2999.invoke(memoize.clj:81)
        at clojure.core.cache$through$fn__2750.invoke(cache.clj:55)
        at clojure.core.memoize$through_STAR_$fn__2995$fn__2996.invoke(memoize.clj:80)
        at clojure.core.memoize.RetryingDelay.deref(memoize.clj:64)
        at clojure.core$deref.invokeStatic(core.clj:2320)
        at clojure.core$deref.invoke(core.clj:2306)
        at clojure.core.memoize$build_memoizer$fn__3058.doInvoke(memoize.clj:167)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at clojure.lang.AFn.applyToHelper(AFn.java:152)
        at clojure.lang.RestFn.applyTo(RestFn.java:132)
        at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
        at clojure.lang.RestFn.invoke(RestFn.java:397)
        at swarmpit.stats$active_hosts.invokeStatic(stats.clj:16)
        at swarmpit.stats$active_hosts.invoke(stats.clj:13)
        at swarmpit.stats$ready_QMARK_.invokeStatic(stats.clj:46)
        at swarmpit.stats$ready_QMARK_.invoke(stats.clj:44)
        at swarmpit.event.rules.subscription_stats$dashboard_data.invokeStatic(subscription_stats.clj:10)
        at swarmpit.event.rules.subscription_stats$dashboard_data.invoke(subscription_stats.clj:8)
        at swarmpit.event.rules.subscription_stats$subscribed_data.invokeStatic(subscription_stats.clj:53)
        at swarmpit.event.rules.subscription_stats$subscribed_data.invoke(subscription_stats.clj:50)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309$fn__19317.invoke(channel.clj:76)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309.invoke(channel.clj:73)
        at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307.invoke(channel.clj:71)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
        at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
        at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
        at swarmpit.event.channel$broadcast_statistics$fn__19306.invoke(channel.clj:71)
        at clojure.lang.AFn.run(AFn.java:22)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Steps to reproduce the issue:**
1. Install swarmpit with [docker-compose](https://github.com/swarmpit/swarmpit/blob/master/docker-compose.yml) 
2. Add the SWARMPIT_DOCKER_HTTP_TIMEOUT environment variable set to 30000
3. Restart the stack and access the web site.
4. Click on stacks section

**What happens:**
A red popup with "java.lang.String cannot be cast to java.lang.Number" is shown

**What should happen:**
See all the docker stacks without errors, stacks are not shown.

**Additional information (e.g. docker version, cluster setup,...):**
Needed this configuration because request takes longer then 5 seconds default timeout.

**Comment by nohaapav** [comment]
There is a bug. This value is currently parsed as string (whole ENV property array is). Will prepare fix asap.

**Comment by nohaapav** [comment]
@mapo-job Should be fixed in master

**Comment by canidam** [comment]
@nohaapav thanks. Is there a way to deploy it from dockerhub?

**Comment by Thiritin** [comment]
@nohaapav @mapo-job shouldn't this be added as a hotfix, is there a workaround for the meantime?
`docker service update swarmpit_app --env-add SWARMPIT_DOCKER_HTTP_TIMEOUT=15000`

**Comment by Thiritin** [comment]
> @nohaapav @mapo-job shouldn't this be added as a hotfix, is there a workaround for the meantime?
> `docker service update swarmpit_app --env-add SWARMPIT_DOCKER_HTTP_TIMEOUT=15000`

Nvm, im just using latest for the meantime.
