### ISSUE TITLE
Memory issue

### ISSUE THREAD

**Issue by vermachandra** [swarmpit/swarmpit#547]
Hi ,

We are observing that every few days GUI does not responds and it needs to be restarted to make it work.

today morning below logs were observed when the same issue occurred. , please help with fixes.  

Mon Aug 10 06:00:31 UTC 2020 [server-loop] ERROR - http server loop error, should not happen
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:695)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)
        at sun.nio.ch.IOUtil.write(IOUtil.java:130)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
        at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)
        at org.httpkit.server.HttpServer.run(HttpServer.java:302)
        at java.lang.Thread.run(Thread.java:748)
Mon Aug 10 06:00:32 UTC 2020 [server-loop] ERROR - http server loop error, should not happen
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:695)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)
        at sun.nio.ch.IOUtil.write(IOUtil.java:130)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
        at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)
        at org.httpkit.server.HttpServer.run(HttpServer.java:302)
        at java.lang.Thread.run(Thread.java:748)
Mon Aug 10 06:00:32 UTC 2020 [server-loop] ERROR - http server loop error, should not happen
java.lang.OutOfMemoryError: Direct buffer memory
        at java.nio.Bits.reserveMemory(Bits.java:695)
        at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
        at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
        at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)
        at sun.nio.ch.IOUtil.write(IOUtil.java:130)
        at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
        at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)
        at org.httpkit.server.HttpServer.run(HttpServer.java:302)
        at java.lang.Thread.run(Thread.java:748)
Mon Aug 10 06:00:33 UTC 2020 [server-loop] ERROR - http server loop error, should not happ

**Comment by nohaapav** [comment]
@vermachandra you probably run out of memory. We'll upgrade http kit in 2.0 to see if problem persist.

**Comment by alfonsodg** [comment]
I have the same problem with the latest version, to fix i need to increase greatly the memory, right now the min is 2 GB and max 4 GB.  By the way, the version 1.8 works fine
![2020-08-26_07-19] (https://user-images.githubusercontent.com/861056/91302788-9de90600-e76c-11ea-94f9-dc7257b69e4f.png)



`
ctions  
      
20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.server:91] - Swarmpit is starting...


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:30] - Waiting for CouchDB ...


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:33] - ... CouchDB connected in 0 sec


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:63] - Swarmpit DB already exist


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:30] - Waiting for InfluxDB ...


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:33] - ... InfluxDB connected in 0 sec


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:76] - InfluxDB RP: #{"autogen" "an_hour" "a_day"}


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.database:77] - InfluxDB CQ: #{"cq_tasks_1m" "cq_hosts_1m" "cq_max_usage_services_30m" "cq_services_1m"}


20-08-26 12:15:05 7b778fede2c3 INFO [swarmpit.server:95] - Swarmpit running on port 8080


20-08-26 12:15:06 7b778fede2c3 INFO [swarmpit.setup:14] - Docker API: 1.40


20-08-26 12:15:06 7b778fede2c3 INFO [swarmpit.setup:15] - Docker ENGINE: 19.03.12


20-08-26 12:15:06 7b778fede2c3 INFO [swarmpit.setup:16] - Docker SOCK: /var/run/docker.sock


20-08-26 12:15:06 7b778fede2c3 INFO [swarmpit.setup:21] - Log level: info


java.lang.OutOfMemoryError: Direct buffer memory


	at java.nio.Bits.reserveMemory(Bits.java:695)


	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)


	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)


	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)


	at sun.nio.ch.IOUtil.write(IOUtil.java:130)


	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)


	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)


	at org.httpkit.server.HttpServer.run(HttpServer.java:302)


	at java.lang.Thread.run(Thread.java:748)


Tue Aug 25 20:10:26 PET 2020 [server-loop] ERROR - http server loop error, should not happen


java.lang.OutOfMemoryError: Direct buffer memory


	at java.nio.Bits.reserveMemory(Bits.java:695)


	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)


	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)


	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)


	at sun.nio.ch.IOUtil.write(IOUtil.java:130)


	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)


	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)


	at org.httpkit.server.HttpServer.run(HttpServer.java:302)


	at java.lang.Thread.run(Thread.java:748)


Tue Aug 25 20:10:27 PET 2020 [server-loop] ERROR - http server loop error, should not happen


java.lang.OutOfMemoryError: Direct buffer memory


	at java.nio.Bits.reserveMemory(Bits.java:695)


	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)


	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)


	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)


	at sun.nio.ch.IOUtil.write(IOUtil.java:130)


	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)


	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)


	at org.httpkit.server.HttpServer.run(HttpServer.java:302)


	at java.lang.Thread.run(Thread.java:748)


Tue Aug 25 20:12:01 PET 2020 [server-loop] ERROR - http server loop error, should not happen


java.lang.OutOfMemoryError: Direct buffer memory


	at java.nio.Bits.reserveMemory(Bits.java:695)


	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)


	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)


	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)


	at sun.nio.ch.IOUtil.write(IOUtil.java:130)


	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)


	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)


	at org.httpkit.server.HttpServer.run(HttpServer.java:302)


	at java.lang.Thread.run(Thread.java:748)


Tue Aug 25 20:12:06 PET 2020 [server-loop] ERROR - http server loop error, should not happen


java.lang.OutOfMemoryError: Direct buffer memory


	at java.nio.Bits.reserveMemory(Bits.java:695)


	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)


	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)


	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)


	at sun.nio.ch.IOUtil.write(IOUtil.java:130)


	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)


	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)


	at org.httpkit.server.HttpServer.run(HttpServer.java:302)


	at java.lang.Thread.run(Thread.java:748)


Exception in thread "async-dispatch-4" java.lang.OutOfMemoryError: Java heap space


	at java.util.Arrays.copyOf(Arrays.java:3332)


	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)


	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)


	at java.lang.StringBuilder.append(StringBuilder.java:136)


	at clojure.core$str$fn__5451.invoke(core.clj:557)


	at clojure.core$str.invokeStatic(core.clj:555)


	at clojure.core$str.doInvoke(core.clj:544)


	at clojure.lang.RestFn.invoke(RestFn.java:439)


	at swarmpit.event.channel$event_data.invokeStatic(channel.clj:18)


	at swarmpit.event.channel$event_data.invoke(channel.clj:16)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543$fn__21545$fn__21553.invoke(channel.clj:77)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543$fn__21545.invoke(channel.clj:73)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543.invoke(channel.clj:71)


	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)


	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)


	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)


	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)


	at swarmpit.event.channel$broadcast_statistics$fn__21542.invoke(channel.clj:71)


	at clojure.lang.AFn.run(AFn.java:22)


	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


	at java.lang.Thread.run(Thread.java:748)


Exception in thread "async-dispatch-2" java.lang.OutOfMemoryError: Java heap space


	at java.util.Arrays.copyOf(Arrays.java:3332)


	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:124)


	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:448)


	at java.lang.StringBuilder.append(StringBuilder.java:136)


	at clojure.core$str$fn__5451.invoke(core.clj:557)


	at clojure.core$str.invokeStatic(core.clj:555)


	at clojure.core$str.doInvoke(core.clj:544)


	at clojure.lang.RestFn.invoke(RestFn.java:439)


	at swarmpit.event.channel$event_data.invokeStatic(channel.clj:18)


	at swarmpit.event.channel$event_data.invoke(channel.clj:16)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543$fn__21545$fn__21553.invoke(channel.clj:77)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543$fn__21545.invoke(channel.clj:73)


	at swarmpit.event.channel$broadcast_statistics$fn__21542$state_machine__10196__auto____21543.invoke(channel.clj:71)


	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)


	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)


	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)


	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)


	at swarmpit.event.channel$broadcast_statistics$fn__21542.invoke(channel.clj:71)


	at clojure.lang.AFn.run(AFn.java:22)


	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)


	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


	at java.lang.Thread.run(Thread.java:748)
`

**Comment by nohaapav** [comment]
I latest version we upgrade JRE from 8 to 11 as well as http-client which should fix thread leak. See: https://github.com/swarmpit/swarmpit/pull/546

**Comment by ramonck** [comment]
I'm also going to complain about memory but I will do it in another ticket, it's insane the difference of memory consumption.

**Comment by alfonsodg** [comment]
Hi,

The problem is still present.  I need to restart the service every time.  I need to return to 1.8.  I have a lot of resources as you can see

![2020-09-07_14-08](https://user-images.githubusercontent.com/861056/92413001-c4675380-f113-11ea-8c59-f27f2cef5dfd.png)

**Comment by nohaapav** [comment]
@alfonsodg Can you check if you're facing same problem with `1.9` version ? Or just `latest` ?

**Comment by lightningspirit** [comment]
I can relate to that. This issue is happening to me in 1.9 release. Minimum resources allocated with 2GB memory.
From time to time it needs to be restarted.
```
Fri Apr 02 14:13:21 UTC 2021 [server-loop] ERROR - http server loop error, should not happen
java.lang.OutOfMemoryError: Direct buffer memory
	at java.nio.Bits.reserveMemory(Bits.java:695)
	at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
	at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:311)
	at sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:241)
	at sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:501)
	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:210)
	at org.httpkit.server.HttpServer.run(HttpServer.java:302)
	at java.lang.Thread.run(Thread.java:748)
```
If you need anything more for testing purposes, please advise.

**Comment by nohaapav** [comment]
@lightningspirit Upgrade to latest version (1.10). There is new version of http kit.

**Comment by lightningspirit** [comment]
@nohaapav didn't notice there was a 1.10 version 🤔 totally missed that!
I will upgrade to 1.10 and ping you back if I encounter any problems.

**Comment by 2peter3** [comment]
Hey im using v1.10-38ffbe0 with 42 Nodes and getting the same error

```
Sat Apr 10 22:12:42 UTC 2021 [server-loop] ERROR - http server loop error, should not happen
java.lang.OutOfMemoryError: Direct buffer memory
	at java.base/java.nio.Bits.reserveMemory(Bits.java:175)
	at java.base/java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:118)
	at java.base/java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:317)
	at java.base/sun.nio.ch.Util.getTemporaryDirectBuffer(Util.java:242)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:164)
	at java.base/sun.nio.ch.IOUtil.write(IOUtil.java:130)
	at java.base/sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:496)
	at org.httpkit.server.HttpServer.doWrite(HttpServer.java:280)
	at org.httpkit.server.HttpServer.run(HttpServer.java:376)
	at java.base/java.lang.Thread.run(Thread.java:834)
```
Do you have any hint how to workaround this error

**Comment by nohaapav** [comment]
See related issue: https://github.com/swarmpit/swarmpit/issues/551

We're digging into issue with profiler and it looks the cause is related to influx and data being displayed. If you disable influx (no dashboards) Swarmpit should work without any memory issue. As temporary fix.

**Comment by DannyDevil0** [comment]
Facing same issue
![image](https://user-images.githubusercontent.com/35533970/115271579-1c127680-a15b-11eb-922e-403c6e5e063e.png)

**Comment by constantx** [comment]
Same.

**Comment by SaimonL** [comment]
I had similar issue. I am using "swarmpit/swarmpit:1.9" and I have noticed that during idle it does not take any resources. I have 3 workers in the swarm cluster. I am using "gluster" to sync files in-between the nodes.

As soon as I deployed my first mongodb service (not stack) and allocated 1GB or ram and 2GB max it ran ok and after a minute I saw my CPU usage going up and my ram using went to 99% (23 GB). It stayed there for 5 minutes before going back down to 755 MB of ram usage. There were a lots of "java -jar swarmpit.jar" running around (100) and "/usr/sbin/docker" was taking up lots of CPU. It did not affected my other worker nodes. 
 
![ui-memory](https://user-images.githubusercontent.com/7557791/125609376-53d91793-9be0-4a60-92a2-b33f2aef1e99.jpg)

![cluster](https://user-images.githubusercontent.com/7557791/125609399-04a22aee-3d6b-4398-b892-96778165a957.jpg)

![htop](https://user-images.githubusercontent.com/7557791/125609417-d2e089a9-4655-44e7-906f-3effb1b56570.jpg)

Later on I saw this issue moved to one of my other node

![newplot](https://user-images.githubusercontent.com/7557791/125612116-3f2e2249-7628-42af-af3d-72f790581bb6.png)
