### ISSUE TITLE
swarmpit not starting after reboot

### ISSUE THREAD

**Issue by bd8392** [swarmpit/swarmpit#553]
---------------------------------------------------
BUG REPORT
---------------------------------------------------
-->

**Description**

**Steps to reproduce the issue:**
1. deploy swarmpit on a single node in docker-swarm mode
2. reboot
3. suddenly no function

**Additional information (e.g. docker version, cluster setup,...):**

single node cluster for testing, docker 19.03.11

**Comment by nohaapav** [comment]
@bd8392 Well the question is why Swarmpit couldn't join Influx. Maybe matter of setup so more details would be great. It's hard for us to reproduce the case as we're not facing any influx issues whatever cluster it is.

**Comment by n1ru4l** [comment]
I had an issue that SwarmPit was unable to query the data. After tearing down the stack, purging the influx volume and redeploying the stack everything seems to work again.

We are running a two-node docker swarm. I experienced this issue for the first time.

The endpoints for querying the UI data responded with the following text content: `Malformed application/json in :muuntaja/encode`

**Comment by nohaapav** [comment]
@n1ru4l Looks like invalid data format according backend API spec were returned. Do you remember which API responded 
with `Malformed application/json in :muuntaja/encode` ?

**Comment by n1ru4l** [comment]
@nohaapav It was the `/cpu` and `/memory` endpoints.

The logs showed something like this, unfortunately, I do not have any more information. The stack was running for a long time before this issue occured.

```
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | clojure.lang.ExceptionInfo: DB failure: db {:status 500, :type :http-client, :body {:error "db"}}
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.http$execute_in_scope.invokeStatic(http.clj:68)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.http$execute_in_scope.invoke(http.clj:54)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.couchdb.client$execute.invokeStatic(client.clj:10)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.couchdb.client$execute.invoke(client.clj:7)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.couchdb.client$find_docs.invokeStatic(client.clj:47)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.couchdb.client$find_docs.invoke(client.clj:43)
swarm-pit-stack_app.1.z7qi2icgzkkl@outer-space    | 	at swarmpit.couchdb.client$find_doc.invokeStatic(client.clj:57)
swarm-pit-stack_app.1.w6i6aqajb44z@outer-space    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
swarm-pit-stack_app.1.w6i6aqajb44z@outer-space    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
swarm-pit-stack_app.1.w6i6aqajb44z@outer-space    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
swarm-pit-stack_app.1.w6i6aqajb44z@outer-space    | 	at java.lang.Thread.run(Thread.java:748)
```

**Comment by bd8392** [comment]
> @bd8392 Well the question is why Swarmpit couldn't join Influx. Maybe matter of setup so more details would be great. It's hard for us to reproduce the case as we're not facing any influx issues whatever cluster it is.

Oh okay I'm very sorry I forgot about...

The setup is the same as if out of your docker-compose file. I leaved it as it is...I only have one node...the problem is, that I tried to reproduce myself and it only happens on occasion...most reboots work, and the suddenly one doesn't...I also fixed it by purging the influxdb volume...no everything seems to be running...

**Comment by nohaapav** [comment]
@n1ru4l Thanks. The logs are related to DB not statistics in this case so this is not relevant info. 

`/services/cpu` & `/services/memory` endpoints might be the case. Although it would be great to know the response so we know what to debug.

@bd8392 Strange that you're getting `Connection refused (Connection refused)`. Looks to me like as a network issue. Swarmpit is trying to reach influx but can't. The question is if port / ip of influx container is somehow fishy or influx container. Next time this happens can you EXEC into swarmpit_app or swarmpit_db container and ping influx if you get the response ?

`curl influxdb:8086/ping`

**Comment by n1ru4l** [comment]
@nohaapav Sorry I have no other debug information available. The response was actually plain text as I remember.

**Comment by nohaapav** [comment]
@n1ru4l Plain text is most probably stacktrace ..

**Comment by mrspartak** [comment]
Hello. I've got the same problem for the first time. /cpu /memory are not responding.
The response error is just plain text 
```
Malformed application/json in :muuntaja/encode
```
This is log from app
```
gww5v  Exception in thread "async-dispatch-34600" clojure.lang.ExceptionInfo: clj-http: status 404 {:cached nil, :request-time 3, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :http-client #object[org.apache.http.impl.client.InternalHttpClient 0x2801f4ba "org.apache.http.impl.client.InternalHttpClient@2801f4ba"], :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Not Found", :headers {"X-Influxdb-Build" "OSS", "Content-Type" "application/json", "Content-Length" "45", "Connection" "close", "X-Influxdb-Error" "database not found: \"swarmpit\"", "X-Influxdb-Version" "1.7.11", "Date" "Mon, 21 Feb 2022 10:49:56 GMT", "Request-Id" "021edc24-9304-11ec-808a-02420a000125", "X-Request-Id" "021edc24-9304-11ec-808a-02420a000125"}, :orig-content-encoding nil, :status 404, :length 45, :body "{\"error\":\"database not found: \\\"swarmpit\\\"\"}\n", :trace-redirects []}
gww5v  	at slingshot.support$stack_trace.invoke(support.clj:201)
gww5v  	at clj_http.client$exceptions_response.invokeStatic(client.clj:240)
gww5v  	at clj_http.client$exceptions_response.invoke(client.clj:231)
gww5v  	at clj_http.client$wrap_exceptions$fn__5452.invoke(client.clj:249)
gww5v  	at clj_http.client$wrap_accept$fn__5662.invoke(client.clj:726)
gww5v  	at clj_http.client$wrap_accept_encoding$fn__5669.invoke(client.clj:748)
gww5v  	at clj_http.client$wrap_content_type$fn__5656.invoke(client.clj:709)
gww5v  	at clj_http.client$wrap_form_params$fn__5755.invoke(client.clj:950)
gww5v  	at clj_http.client$wrap_nested_params$fn__5776.invoke(client.clj:984)
gww5v  	at clj_http.client$wrap_flatten_nested_params$fn__5785.invoke(client.clj:1008)
gww5v  	at clj_http.client$wrap_method$fn__5723.invoke(client.clj:884)
gww5v  	at clj_http.cookies$wrap_cookies$fn__3965.invoke(cookies.clj:131)
gww5v  	at clj_http.links$wrap_links$fn__5091.invoke(links.clj:63)
gww5v  	at clj_http.client$wrap_unknown_host$fn__5793.invoke(client.clj:1037)
gww5v  	at clj_http.client$request_STAR_.invokeStatic(client.clj:1165)
gww5v  	at clj_http.client$request_STAR_.invoke(client.clj:1158)
gww5v  	at clj_http.client$post.invokeStatic(client.clj:1183)
gww5v  	at clj_http.client$post.doInvoke(client.clj:1179)
gww5v  	at clojure.lang.RestFn.invoke(RestFn.java:423)
gww5v  	at influxdb.client$write.invokeStatic(client.clj:46)
gww5v  	at influxdb.client$write.invoke(client.clj:41)
gww5v  	at influxdb.client$write.invokeStatic(client.clj:44)
gww5v  	at influxdb.client$write.invoke(client.clj:41)
gww5v  	at swarmpit.influxdb.client$write_doc$fn__15002.invoke(client.clj:32)
gww5v  	at swarmpit.influxdb.client$execute.invokeStatic(client.clj:11)
gww5v  	at swarmpit.influxdb.client$execute.invoke(client.clj:9)
gww5v  	at swarmpit.influxdb.client$write_doc.invokeStatic(client.clj:31)
gww5v  	at swarmpit.influxdb.client$write_doc.invoke(client.clj:29)
gww5v  	at swarmpit.influxdb.client$write_host_points.invokeStatic(client.clj:165)
gww5v  	at swarmpit.influxdb.client$write_host_points.invoke(client.clj:163)
gww5v  	at swarmpit.stats$store_to_db.invokeStatic(stats.clj:58)
gww5v  	at swarmpit.stats$store_to_db.invoke(stats.clj:53)
gww5v  	at swarmpit.event.rules.processing$reify__22728.process(processing.clj:19)
gww5v  	at swarmpit.event.processor$process$fn__22750$state_machine__10138__auto____22761$fn__22763$fn__22769.invoke(processor.clj:10)
gww5v  	at swarmpit.event.processor$process$fn__22750$state_machine__10138__auto____22761$fn__22763.invoke(processor.clj:9)
gww5v  	at swarmpit.event.processor$process$fn__22750$state_machine__10138__auto____22761.invoke(processor.clj:8)
gww5v  	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:978)
gww5v  	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:977)
gww5v  	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:982)
gww5v  	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:980)
gww5v  	at swarmpit.event.processor$process$fn__22750.invoke(processor.clj:8)
gww5v  	at clojure.lang.AFn.run(AFn.java:22)
gww5v  	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
gww5v  	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
gww5v  	at clojure.core.async.impl.concurrent$counted_thread_factory$reify__6236$fn__6237.invoke(concurrent.clj:29)
gww5v  	at clojure.lang.AFn.run(AFn.java:22)
gww5v  	at java.base/java.lang.Thread.run(Thread.java:829)
```

This is log from InfluxDB
```
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:05 +0000] "POST /write?db=swarmpit HTTP/1.1" 404 45 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 4ee7c3cb-9304-11ec-8096-02420a000125 268
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:19 +0000] "GET /query?q=SELECT+cpu%2C+memory%0A++++++++++FROM+swarmpit.a_day.downsampled_services%0A++++++++++WHERE+%0A++++++++++GROUP+BY+service HTTP/1.1" 400 107 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 575e6ebd-9304-11ec-8097-02420a000125 380
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:19 +0000] "GET /query?q=SELECT+cpu%2C+memory%0A++++++++++FROM+swarmpit.a_day.downsampled_services%0A++++++++++WHERE+%0A++++++++++GROUP+BY+service HTTP/1.1" 400 107 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 576d9c2b-9304-11ec-8098-02420a000125 219
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:19 +0000] "GET /query?q=SELECT+cpu%2C+memory%0A++++++FROM+swarmpit.a_day.downsampled_hosts%0A++++++GROUP+BY+host HTTP/1.1" 200 95 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 578c0669-9304-11ec-8099-02420a000125 1152
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:24 +0000] "POST /write?db=swarmpit HTTP/1.1" 404 45 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 5a426e09-9304-11ec-809a-02420a000125 179
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:25 +0000] "GET /query?q=SELECT+cpu%2C+memory%0A++++++++++FROM+swarmpit.a_day.downsampled_services%0A++++++++++WHERE+%0A++++++++++GROUP+BY+service HTTP/1.1" 400 107 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 5aa0f640-9304-11ec-809b-02420a000125 320
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:30 +0000] "POST /write?db=swarmpit HTTP/1.1" 404 45 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 5ddc2779-9304-11ec-809c-02420a000125 91
snr4x  [httpd] 10.0.1.12 - - [21/Feb/2022:10:52:31 +0000] "GET /query?q=SELECT+cpu%2C+memory%0A++++++++++FROM+swarmpit.a_day.downsampled_services%0A++++++++++WHERE+%0A++++++++++GROUP+BY+service HTTP/1.1" 400 107 "-" "Apache-HttpClient/4.5.10 (Java/11.0.11)" 5e34718c-9304-11ec-809d-02420a000125 279
```

**Comment by Radiergummi** [comment]
In my case, I'm running swarmpit under a different name (`swarmpit` instead of `app`). The agent [seems to expect `app`](https://github.com/swarmpit/agent#parameters) for its endpoints though, so you'll need to define these manually:
```yaml
  swarmpit_agent:
    image: swarmpit/agent:latest
    environment:
      - DOCKER_API_VERSION=1.35
      - EVENT_ENDPOINT=http://<NAME_OF_YOUR_SWARMPIT_SERVICE>:8080/events
      - HEALTH_CHECK_ENDPOINT=http://<NAME_OF_YOUR_SWARMPIT_SERVICE>:8080/version
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - swarmpit
    deploy:
      mode: global
      resources:
        limits:
          cpus: '0.10'
          memory: 64M
        reservations:
          cpus: '0.05'
          memory: 32M
```

After a few minutes, stats appeared. Just in case anyone hits the same obstacle.
