### ISSUE TITLE
Configure SWARMPIT_DOCKER_HTTP_TIMEOUT crashes with java.lang.String cannot be cast to java.lang.Number exception

### ISSUE THREAD

**Issue by canidam** [swarmpit/swarmpit#558]
---------------------------------------------------
BUG REPORT
---------------------------------------------------

**Description**

Fetching services logs from Swarmpit fails with "Couldn't fetch service logs" errors, for some services. 
I'm trying to increase the timeout, but configuring **SWARMPIT_DOCKER_HTTP_TIMEOUT** env variable on swarmpit app throws an exception, which breaks the app - it is no longer collecting or presenting any data.

I have tried multiple values, with 30s, 10s and last I tried to set the default value:
```
      - SWARMPIT_DOCKER_HTTP_TIMEOUT=30000
      - SWARMPIT_DOCKER_HTTP_TIMEOUT=10000
      - SWARMPIT_DOCKER_HTTP_TIMEOUT=5000
```

Removing this env param solves the issue.

**Steps to reproduce the issue:**
1. Configure **SWARMPIT_DOCKER_HTTP_TIMEOUT** on the app service, with any value and deploy the stack

**What happens:**
 ```
Sep 22, 2020 5:34:11 PM swarmpit.server invoke
 INFO: Swarmpit is starting...
 Sep 22, 2020 5:34:11 PM swarmpit.database invoke
 INFO: Waiting for CouchDB ...
 Sep 22, 2020 5:34:12 PM swarmpit.database invoke
 INFO: ... connected after 0 sec
 Sep 22, 2020 5:34:12 PM swarmpit.database invoke
 INFO: Waiting for InfluxDB ...
 Sep 22, 2020 5:34:12 PM swarmpit.database invoke
 INFO: ... connected after 0 sec
 Sep 22, 2020 5:34:13 PM swarmpit.database invoke
 INFO: InfluxDB RP: #{autogen an_hour a_day}
 Sep 22, 2020 5:34:13 PM swarmpit.database invoke
 INFO: InfluxDB CQ: #{}
 Sep 22, 2020 5:34:13 PM swarmpit.server invoke
 INFO: Swarmpit running on port 8080
 Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Number
 	at clojure.core$deref.invokeStatic(core.clj:2323)
 	at clojure.core$deref.invoke(core.clj:2306)
 	at swarmpit.http$execute_in_scope$fn__6006.invoke(http.clj:60)
 	at swarmpit.http$execute_in_scope.invokeStatic(http.clj:60)
 	at swarmpit.http$execute_in_scope.invoke(http.clj:54)
 	at swarmpit.docker.engine.http$execute.invokeStatic(http.clj:39)
 	at swarmpit.docker.engine.http$execute.invoke(http.clj:37)
 	at swarmpit.docker.engine.client$version.invokeStatic(client.clj:316)
 	at swarmpit.docker.engine.client$version.invoke(client.clj:314)
 	at swarmpit.setup$docker.invokeStatic(setup.clj:8)
 	at swarmpit.setup$docker.invoke(setup.clj:6)
 	at swarmpit.server$_main.invokeStatic(server.clj:97)
 	at swarmpit.server$_main.doInvoke(server.clj:90)
 	at clojure.lang.RestFn.invoke(RestFn.java:397)
 	at clojure.lang.AFn.applyToHelper(AFn.java:152)
 	at clojure.lang.RestFn.applyTo(RestFn.java:132)
 	at swarmpit.server.main(Unknown Source)
```

**What should happen:**
The Docker HTTP timeout should be increased, preferably to large number up to few min.

**Additional information (e.g. docker version, cluster setup,...):**
I reproduced the issue on v1.9.

Docker version
```
Client: Docker Engine - Community
 Version:           19.03.12
 API version:       1.40
 Go version:        go1.13.10
 Git commit:        48a66213fe
 Built:             Mon Jun 22 15:45:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.12
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.10
  Git commit:       48a66213fe
  Built:            Mon Jun 22 15:44:07 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.2.13
  GitCommit:        7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Comment by nohaapav** [comment]
@canidam it's fixed in master ..

See https://github.com/swarmpit/swarmpit/issues/511

**Comment by canidam** [comment]
@nohaapav thanks. Is there a way to deploy it from dockerhub?

**Comment by nohaapav** [comment]
@canidam master is basically latest :)

**Comment by canidam** [comment]
Thanks, I tested it with `latest` image now - it works
