### ISSUE TITLE
i would like to install and use swarmpit but i don't want to collect statistics ( influxdb ) only real time data 

### ISSUE THREAD

**Issue by ctamietto** [swarmpit/swarmpit#585]
**Description**

**Steps to reproduce the issue:**
1.
2.
3.

**What happens:**

**What should happen:**

**Additional information (e.g. docker version, cluster setup,...):**

**Comment by ctamietto** [comment]
is it possible ?

**Comment by nohaapav** [comment]
Just leave `SWARMPIT_INFLUXDB` env variable empty or remove it from `swarmpit_app` service config.

**Comment by markfqs** [comment]
Removing SWARMPIT_INFLUXDB seems to break the stack:

```
Exception in thread "main" java.lang.IllegalArgumentException: Additional data must be non-nil.,
21-03-19 11:49:35 f1315ab5bbe8 ERROR [swarmpit.database:36] - ... InfluxDB connection timeout,
	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:31),
	at clojure.lang.ExceptionInfo.<init>(ExceptionInfo.java:22),
	at clojure.core$ex_info.invokeStatic(core.clj:4783),
	at swarmpit.server.main(Unknown Source),
	at swarmpit.database$wait_for_db.invokeStatic(database.clj:37),
	at clojure.lang.RestFn.applyTo(RestFn.java:132),
	at clojure.lang.AFn.applyToHelper(AFn.java:152),
	at clojure.lang.RestFn.invoke(RestFn.java:397),
	at swarmpit.server$_main.doInvoke(server.clj:90),
	at swarmpit.server$_main.invokeStatic(server.clj:92),
	at swarmpit.database$init.invoke(database.clj:79),
	at swarmpit.database$init.invokeStatic(database.clj:82),
	at swarmpit.database$init_influx.invoke(database.clj:69),
	at swarmpit.database$init_influx.invokeStatic(database.clj:73),
	at swarmpit.database$wait_for_db.invoke(database.clj:28),
	at clojure.core$ex_info.invoke(core.clj:4783)
```

**Comment by nohaapav** [comment]
What version are u using? 

[See this thread](https://github.com/swarmpit/swarmpit/issues/392)

**Comment by markfqs** [comment]
1.10-38ffbe0 is the version shown by the WebUI.

I'm running the ARM 'latest' docker image from docker hub, the inspect on the image gives the following:

[
    {
        "Id": "sha256:f0284b4d91e6c53e0698a8f5d28b6e38d8acd83c1a74ffff5b822952e3dbb176",
        "RepoTags": [],
        "RepoDigests": [
            "swarmpit/swarmpit@sha256:5880f60368f9fc29284dad7d9ef7562bc21b8574fad25ef7341618892be6556a"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2021-03-23T05:10:10.76275512Z",
        "Container": "",
...

**Comment by nohaapav** [comment]
Strange. I do not use ARM based Swarmpit, however it should not be any difference as logic is located [here](https://github.com/swarmpit/swarmpit/blob/master/src/clj/swarmpit/database.clj#L69)

If ENV property is not SET, influx does not get initialized.
