### ISSUE TITLE
Installation issues on Debian 12

### ISSUE THREAD

**Issue by fsimonjetz** [swarmpit/swarmpit#688]
**Description**

We need to migrate our 2-node swarm to new infrastructure and I have been trying to get Swarmpit to run for a week without avail.

**Steps to reproduce the issue:**

1. Create a swarm on the first machine
2. Join the 2nd machine to the swarm as worker
3. Run the setup script on the first node
  ```sh
  docker run -it --rm \
  --name swarmpit-installer \
  --volume /var/run/docker.sock:/var/run/docker.sock \
  swarmpit/install:1.9
  ```

**What happens:**

After going to through the installation, leaving all options on default the script fails:

```
Starting swarmpit.......................FAILED!
Swarmpit is not responding for a long time. Aborting installation...:(
Please check logs and cluster status for details.
```

I see the following on the manager node:

```
$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED         STATUS         PORTS      NAMES
ad0fcbbc68e2   swarmpit/swarmpit:1.9   "java -jar swarmpit.…"   4 minutes ago   Up 4 minutes   8080/tcp   ...
4bf418e65c47   swarmpit/agent:2.2      "./agent"                4 minutes ago   Up 4 minutes   8080/tcp   ...


$ docker logs ad0fcbbc68e2
Jun 10, 2024 9:35:07 AM swarmpit.server invoke
INFO: Swarmpit is starting...
Jun 10, 2024 9:35:07 AM swarmpit.database invoke
INFO: Waiting for CouchDB ...


$ docker logs 4bf418e65c47
2024/06/10 09:34:37 INFO: Waiting for Swarmpit...
```

and on the worker node:

```
$ docker ps
CONTAINER ID   IMAGE                COMMAND                  CREATED         STATUS         PORTS                          NAMES
61ad4d6c13d6   influxdb:1.7         "/entrypoint.sh infl…"   4 minutes ago   Up 4 minutes   8086/tcp                       ...
4e2a61788a25   couchdb:2.3.0        "tini -- /docker-ent…"   4 minutes ago   Up 4 minutes   4369/tcp, 5984/tcp, 9100/tcp   ...
8733a83ade54   swarmpit/agent:2.2   "./agent"                4 minutes ago   Up 4 minutes   8080/tcp                       ...


$ docker logs 61ad4d6c13d6 -n 5
ts=2024-06-10T09:34:57.247773Z lvl=info msg="Storing statistics" log_id=0phNrMU0000 service=monitor db_instance=_internal db_rp=monitor interval=10s
ts=2024-06-10T09:34:57.247860Z lvl=info msg="Listening on HTTP" log_id=0phNrMU0000 service=httpd addr=[::]:8086 https=false
ts=2024-06-10T09:34:57.247892Z lvl=info msg="Starting retention policy enforcement service" log_id=0phNrMU0000 service=retention check_interval=30m
ts=2024-06-10T09:34:57.247997Z lvl=info msg="Listening for signals" log_id=0phNrMU0000
ts=2024-06-10T09:34:57.248075Z lvl=info msg="Sending usage statistics to usage.influxdata.com" log_id=0phNrMU0000


$ docker logs 4e2a61788a25 -n 5
[notice] 2024-06-10T09:41:40.030477Z nonode@nohost <0.343.0> -------- chttpd_auth_cache changes listener died database_does_not_exist at mem3_shards:load_shards_from_db/6(line:395) <= mem3_shards:load_shards_from_disk/1(line:370) <= mem3_shards:load_shards_from_disk/2(line:399) <= mem3_shards:for_docid/3(line:86) <= fabric_doc_open:go/3(line:39) <= chttpd_auth_cache:ensure_auth_ddoc_exists/2(line:195) <= chttpd_auth_cache:listen_for_changes/1(line:142)
[error] 2024-06-10T09:41:40.030517Z nonode@nohost emulator -------- Error in process <0.7062.0> with exit value:
{database_does_not_exist,[{mem3_shards,load_shards_from_db,"_users",[{file,"src/mem3_shards.erl"},{line,395}]},{mem3_shards,load_shards_from_disk,1,[{file,"src/mem3_shards.erl"},{line,370}]},{mem3_shards,load_shards_from_disk,2,[{file,"src/mem3_shards.erl"},{line,399}]},{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,86}]},{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},{chttpd_auth_cache,ensure_auth_ddoc_exists,2,[{file,"src/chttpd_auth_cache.erl"},{line,195}]},{chttpd_auth_cache,listen_for_changes,1,[{file,"src/chttpd_auth_cache.erl"},{line,142}]}]}

$ docker logs 8733a83ade54
2024/06/10 09:34:37 INFO: Waiting for Swarmpit...
```

If I remove the worker node from the swarm `docker swarm leave`, Swarmpit starts up and I can access the interface.
When re-joining the worker to the swarm, the node shows up in the interface but the stats keep "Loading" similar to [#560](https://github.com/swarmpit/swarmpit/issues/560) and the worker's Swarmpit agent remains in the "Waiting for Swarmpit" state.

In that case, on the manager I get:

```
$ docker ps
CONTAINER ID   IMAGE                   COMMAND                  CREATED          STATUS          PORTS                          NAMES
6cb28c72803a   influxdb:1.7            "/entrypoint.sh infl…"   9 minutes ago    Up 9 minutes    8086/tcp                       ...
b4b04ced2761   couchdb:2.3.0           "tini -- /docker-ent…"   9 minutes ago    Up 9 minutes    4369/tcp, 5984/tcp, 9100/tcp   ...
ad0fcbbc68e2   swarmpit/swarmpit:1.9   "java -jar swarmpit.…"   18 minutes ago   Up 18 minutes   8080/tcp                       ...
4bf418e65c47   swarmpit/agent:2.2      "./agent"                18 minutes ago   Up 18 minutes   8080/tcp                       ...


$ docker logs 6cb28c72803a -n 5
[httpd] 10.0.1.5 - - [10/Jun/2024:09:54:06 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_242)" 6002ea5d-270f-11ef-806a-02420a000121 1092
[httpd] 10.0.1.5 - - [10/Jun/2024:09:54:06 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_242)" 600361f4-270f-11ef-806b-02420a000121 682
[httpd] 10.0.1.5 - - [10/Jun/2024:09:54:06 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_242)" 6003bfc8-270f-11ef-806c-02420a000121 778
[httpd] 10.0.1.5 - - [10/Jun/2024:09:54:06 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_242)" 6004231c-270f-11ef-806d-02420a000121 672
[httpd] 10.0.1.5 - - [10/Jun/2024:09:54:06 +0000] "POST /write?db=swarmpit HTTP/1.1" 204 0 "-" "Apache-HttpClient/4.5.5 (Java/1.8.0_242)" 60049ef3-270f-11ef-806e-02420a000121 754


$ docker logs b4b04ced2761 -n 5
[notice] 2024-06-10T09:52:29.928760Z nonode@nohost <0.10434.0> 5f2ebba78a db:5984 10.0.1.5 undefined POST /swarmpit/_find 200 ok 3
[notice] 2024-06-10T09:53:01.969859Z nonode@nohost <0.10987.0> 814347a5af db:5984 10.0.1.5 undefined POST /swarmpit/_find 200 ok 2
[notice] 2024-06-10T09:53:34.011392Z nonode@nohost <0.11511.0> cce4ab49f9 db:5984 10.0.1.5 undefined POST /swarmpit/_find 200 ok 4
[notice] 2024-06-10T09:54:06.054508Z nonode@nohost <0.12108.0> 8c3bd41135 db:5984 10.0.1.5 undefined POST /swarmpit/_find 200 ok 2
[notice] 2024-06-10T09:54:38.100388Z nonode@nohost <0.12632.0> 337691e462 db:5984 10.0.1.5 undefined POST /swarmpit/_find 200 ok 3

$ docker logs ad0fcbbc68e2  # swarmpit app
Exception in thread "async-dispatch-2" clojure.lang.ExceptionInfo: clj-http: status 400 {:request-time 6, :repeatable? false, :protocol-version {:name "HTTP", :major 1, :minor 1}, :streaming? true, :chunked? false, :type :clj-http.client/unexceptional-status, :reason-phrase "Bad Request", :headers {"X-Influxdb-Build" "OSS", "Content-Type" "application/json", "Content-Length" "107", "Connection" "close", "X-Influxdb-Error" "error parsing query: found GROUP, expected identifier, string, number, bool at line 4, char 11", "X-Influxdb-Version" "1.7.11", "Date" "Mon, 10 Jun 2024 09:44:29 GMT", "Request-Id" "08411b9d-270e-11ef-8010-02420a000121", "X-Request-Id" "08411b9d-270e-11ef-8010-02420a000121"}, :orig-content-encoding nil, :status 400, :length 107, :body "{\"error\":\"error parsing query: found GROUP, expected identifier, string, number, bool at line 4, char 11\"}\n", :trace-redirects []}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at clj_http.client$exceptions_response.invokeStatic(client.clj:241)
	at clj_http.client$exceptions_response.invoke(client.clj:232)
	at clj_http.client$wrap_exceptions$fn__5546.invoke(client.clj:250)
	at clj_http.client$wrap_accept$fn__5748.invoke(client.clj:730)
	at clj_http.client$wrap_accept_encoding$fn__5755.invoke(client.clj:752)
	at clj_http.client$wrap_content_type$fn__5742.invoke(client.clj:713)
	at clj_http.client$wrap_form_params$fn__5841.invoke(client.clj:954)
	at clj_http.client$wrap_nested_params$fn__5862.invoke(client.clj:988)
	at clj_http.client$wrap_flatten_nested_params$fn__5871.invoke(client.clj:1012)
	at clj_http.client$wrap_method$fn__5809.invoke(client.clj:888)
	at clj_http.cookies$wrap_cookies$fn__4054.invoke(cookies.clj:131)
	at clj_http.links$wrap_links$fn__5154.invoke(links.clj:63)
	at clj_http.client$wrap_unknown_host$fn__5879.invoke(client.clj:1041)
	at clj_http.client$request_STAR_.invokeStatic(client.clj:1214)
	at clj_http.client$request_STAR_.invoke(client.clj:1207)
	at clj_http.client$get.invokeStatic(client.clj:1220)
	at clj_http.client$get.doInvoke(client.clj:1216)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at influxdb.client$query.invokeStatic(client.clj:36)
	at influxdb.client$query.invoke(client.clj:25)
	at influxdb.client$query.invokeStatic(client.clj:32)
	at influxdb.client$query.invoke(client.clj:25)
	at swarmpit.influxdb.client$read_doc$fn__6213.invoke(client.clj:22)
	at swarmpit.influxdb.client$execute.invokeStatic(client.clj:11)
	at swarmpit.influxdb.client$execute.invoke(client.clj:9)
	at swarmpit.influxdb.client$read_doc.invokeStatic(client.clj:21)
	at swarmpit.influxdb.client$read_doc.invoke(client.clj:19)
	at swarmpit.influxdb.client$read_service_stats.invokeStatic(client.clj:189)
	at swarmpit.influxdb.client$read_service_stats.invoke(client.clj:184)
	at swarmpit.stats$services_timeseries.invokeStatic(stats.clj:150)
	at swarmpit.stats$services_timeseries.invoke(stats.clj:146)
	at swarmpit.stats$services_cpu_timeseries.invokeStatic(stats.clj:163)
	at swarmpit.stats$services_cpu_timeseries.invoke(stats.clj:159)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:665)
	at clojure.core$apply.invoke(core.clj:660)
	at clojure.core.memoize$through_STAR_$fn__2999.invoke(memoize.clj:81)
	at clojure.core.cache$through$fn__2750.invoke(cache.clj:55)
	at clojure.core.memoize$through_STAR_$fn__2995$fn__2996.invoke(memoize.clj:80)
	at clojure.core.memoize.RetryingDelay.deref(memoize.clj:64)
	at clojure.core$deref.invokeStatic(core.clj:2320)
	at clojure.core$deref.invoke(core.clj:2306)
	at clojure.core.memoize$build_memoizer$fn__3058.doInvoke(memoize.clj:167)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at clojure.lang.AFunction$1.doInvoke(AFunction.java:31)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at swarmpit.event.rules.subscription_stats$dashboard_data.invokeStatic(subscription_stats.clj:12)
	at swarmpit.event.rules.subscription_stats$dashboard_data.invoke(subscription_stats.clj:8)
	at swarmpit.event.rules.subscription_stats$subscribed_data.invokeStatic(subscription_stats.clj:53)
	at swarmpit.event.rules.subscription_stats$subscribed_data.invoke(subscription_stats.clj:50)
	at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309$fn__19317.invoke(channel.clj:76)
	at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307$fn__19309.invoke(channel.clj:73)
	at swarmpit.event.channel$broadcast_statistics$fn__19306$state_machine__12108__auto____19307.invoke(channel.clj:71)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invokeStatic(ioc_macros.clj:973)
	at clojure.core.async.impl.ioc_macros$run_state_machine.invoke(ioc_macros.clj:972)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invokeStatic(ioc_macros.clj:977)
	at clojure.core.async.impl.ioc_macros$run_state_machine_wrapped.invoke(ioc_macros.clj:975)
	at swarmpit.event.channel$broadcast_statistics$fn__19306.invoke(channel.clj:71)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


$ docker logs 4bf418e65c47
2024/06/10 09:34:37 INFO: Waiting for Swarmpit...
2024/06/10 09:43:57 INFO: Swarmpit OK
2024/06/10 09:43:57 INFO: Event collector started.
2024/06/10 09:43:57 INFO: Stats collector started.
```

and on the worker:

```
$ docker ps
CONTAINER ID   IMAGE                COMMAND     CREATED         STATUS         PORTS      NAMES
7c5297fe1de7   swarmpit/agent:2.2   "./agent"   9 minutes ago   Up 9 minutes   8080/tcp   ...

$ docker logs 7c5297fe1de7
2024/06/10 09:46:28 INFO: Waiting for Swarmpit...
```

**Additional information (e.g. docker version, cluster setup,...):**

- 2 VMs running Debian 12
- Docker version 23.0.0
- The firewall is configured to allow **all** traffic between the two servers with `ufw allow from xxx.xxx.xxx.xxx` on both with the respective other IP

**Comment by fsimonjetz** [comment]
So after digging some more into it, I found [this post](https://forums.docker.com/t/overlay-network-ping-works-but-http-requests-only-work-within-same-swarm-node-hangs-as-if-messages-dropped-if-to-other-node/127508/2) from the Docker forum and it turns out it's not an issue with Swarmpit or Docker per se but certain OS and Docker combinations that seem to have a bug with internal checksums. It was resolved instantly by running the command below **on all nodes**. So if anybody else experiences connectivity issues across nodes that don't seem to be firewall or configuration related, this may be it.

```sh
ethtool -K ens192 tx-checksum-ip-generic off
```

The name of your interface may be something other than `ens192`, you can find it with `ifconfig`. Also from what I found this may not be persistent across reboots (cf. [here](https://forums.docker.com/t/docker-swarm-issue-with-routing-mesh-not-routing-published-port-on-all-nodes/123780/15) and [here](https://github.com/moby/moby/issues/41775#issuecomment-796883692)).

This can be closed, but since I found this by mere luck and don't really understand how a Docker expert would debug this, I'd greatly appreciate if anyone could enlighten me :) Cheers!
